### ISSUE TITLE
Dependency Parsing

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#157]
Feature Request: Please add dependency parsing to underthesea

**Comment by zeloru** [comment]
Hello,
I found a link that may be helpful:
Parsing English in 500 Lines of Python
https://explosion.ai/blog/parsing-english-in-python

**Comment by rain1024** [comment]
Thanks for your suggestion.

**Comment by rain1024** [comment]
In next version v1.3.x, I will integrate **deep learning** model for dependency parsing. Hope it will come soon 😃

**Comment by rain1024** [comment]
- [ ] Refactor BiaffineDependencyParser module
