### ISSUE TITLE
Feature request: Sentence tokenize (tokenize a string to a list of sentences)

### ISSUE THREAD

**Issue by ttpro1995** [undertheseanlp/underthesea#163]
I would like to request a feature to tokenize input string into a list of sentence.
It would be equivalent to `from nltk.tokenize import sent_tokenize` but for Vietnamese.

```
input = "Con mèo kêu gâu gâu. Con chó kêu meo meo."
expected_output = ['Con mèo kêu gâu gâu.', 'Con chó kêu meo meo.']
```

**Comment by rain1024** [comment]
@ttpro1995 At the moment, I have a simple solution for this task. First, you use tokenize function, then you can split it with a simple regex to split sentence

```python
from underthesea.word_sent.regex_tokenize import tokenize
import re
input = "Con mèo kêu gâu gâu. Con chó kêu meo meo."
text = tokenize(input)
output = re.split(r" \. ?", text)[:-1]
output
# ['Con mèo kêu gâu gâu', 'Con chó kêu meo meo']
```
So we have simple version of `sent_tokenize` function

```python
from underthesea.word_sent.regex_tokenize import tokenize
import re

def sentence_tokenize(input):
    text = tokenize(input)
    output = re.split(r" \. ?", text)
    if output[-1] == '':
        output.pop()
    return output
```

For a complex solution, I think we must consider in paper [Unsupervised Multilingual Sentence
Boundary Detection](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.85.5017&rep=rep1&type=pdf) (Kiss et al. 2006) which describe algorithm implemented in class `nltk.tokenize.PunktSentenceTokenizer`

What do you think?

**Comment by rain1024** [comment]
@ttpro1995 We happy to pronounce that in underthesea 1.1.11, we have `sent_tokenize` function. Please check it out 

```
>>> from underthesea import sent_tokenize
>>> text = "Con mèo kêu gâu gâu. Con chó kêu meo meo."
>>> sent_tokenize(text)
['Con mèo kêu gâu gâu.', 'Con chó kêu meo meo.']
```
