### ISSUE TITLE
Lỗi không chạy được hàm pos_tag

### ISSUE THREAD

**Issue by truchuynh96** [undertheseanlp/underthesea#205]
Cho em hỏi gõ vào một câu tiếng việt nhưng khi gọi hàm pos_tag ra lại không ra tiếng việt sửa như thế nào ạ em cám ơn ad

**Comment by rain1024** [comment]
Chào @truchuynh96 

Em có thể cho anh biết thêm các thông tin chi tiết về lỗi như:

- Em đã chạy câu lệnh gì?
- Kết quả câu lệnh đấy như thế nào?
- Hệ điều hành em sử dụng, em đã cài đặt underthesea như thế nào?

**Comment by rain1024** [comment]
@truchuynh96 anh không nhìn được file đính kèm em gửi. Em gửi lại file đính kèm nhé. Anh nghĩ tốt nhất là nên vào github để post bài. Không nên trả lời trực tiếp ở mail.

Thanks
