### ISSUE TITLE
Phát hành underthesea v1.1.9

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#206]
Hiện tại phiên bản alpha đã đến version 1.1.9a6.

Dũng đánh giá cho anh về tốc độ và độ chính xác của hàm `word_tokenize` so với phiên bản 1.1.8 nhé

**Comment by Vietdung113** [comment]
Em da chay 2 phien ban va thay do chinh xac cua 2 phien ban la nhu nhau. 
Toc do cua ban 1.1.9a6 nhanh hon phien ban 1.1.8
Cu the : 
![1 1 8_1](https://user-images.githubusercontent.com/22492437/47232052-dbeea380-d3f8-11e8-99c8-f680ce34c9dd.png)
![1 1 9a6](https://user-images.githubusercontent.com/22492437/47232064-e1e48480-d3f8-11e8-864e-0e2b8bd2de93.png)
