### ISSUE TITLE
Dữ liệu huấn luyện cho bài toán NER

### ISSUE THREAD

**Issue by voquocbang** [undertheseanlp/underthesea#207]
Chào anh,

Em có một thắc về bộ dữ liệu huấn luyện cho bài toán NER hiện tại mà anh đang dùng có phải là bộ dữ liệu vlsp2018 không ạ.

Em cảm ơn anh.

**Comment by rain1024** [comment]
@voquocbang Không em, hiện tại bộ anh đang dùng là VLSP 2016. Anh cũng đang dự định sẽ train lại trên bộ VLSP 2018.

Cảm ơn em đã quan tâm
