### ISSUE TITLE
SotA comparability

### ISSUE THREAD

**Issue by ogencoglu** [undertheseanlp/underthesea#209]
For state of the art results table in text classification - IMDB, [link](https://github.com/undertheseanlp/underthesea/wiki/DATA-IMDB), not all publications are comparable due to train/test division etc. 

For example, paper by Mousa et al. itself state that 

> only the results of (Schuller et al., 2015) are directly comparable to our results

under their _Related Work_ section.

**Comment by rain1024** [comment]
Thanks for your comment. 

Do you have any suggestion for this issue?

**Comment by ogencoglu** [comment]
A disclaimer about fair comparability
