### ISSUE TITLE
Sentiment Analysis - Tại sao lại return sentiment kèm label

### ISSUE THREAD

**Issue by picosix** [undertheseanlp/underthesea#210]
Ví dụ: CUSTOMER SUPPORT#NEGATIVE

Mình nghĩ nên tách việc đánh sentiment ra thành 2 phần, 1 là đánh giá trạng thái (negative, positive và neutral) và chọn label cho nội dung (Dịch vụ khách hàng, cho vay, ....) sẽ tăng tính chính xác hơn mặc dù việc đó sẽ tăng thời gian train.

**Comment by picosix** [comment]
@rain1024 OK anh. Nếu nhóm có cần lấy data ở các nguồn khác nhau thì e có thể giúp. Hiện e làm phần crawler là chính :D

**Comment by rain1024** [comment]
@picosix Hiện nay với bài toán sentiment, nhóm mình đã có dữ liệu cho domain ngân hàng, nhà hàng và khách sạn (VLSP cung cấp). @picosix đang thu thập dữ liệu theo domain nào nhỉ?

**Comment by picosix** [comment]
@rain1024 Hiện em chỉ lấy theo channel thôi anh, còn người dùng muốn dùng domain nào thì họ sẽ tự config để query theo keyword. Hiện e có thể lấy trên facebook, youtube, instagram và news
