### ISSUE TITLE
What's the tagset used by Underthesea's POS taggers?

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#220]
Hi, I've browsed the documentation but didn't find the tagset used by Underthesea's POS taggers or the corpus used to train the POS tagger.
Could you please provide the description of all possible tags or give a reference to the description of the tagset? (Is it identical to the tagset used by Pyvi's POS tagger as described in its README page?)

**Comment by rain1024** [comment]
@BLKSerene You can find full tagset here https://github.com/undertheseanlp/underthesea/wiki/M%C3%B4-t%E1%BA%A3-d%E1%BB%AF-li%E1%BB%87u-b%C3%A0i-to%C3%A1n-POS-Tag

**Comment by BLKSerene** [comment]
Thanks!
