### ISSUE TITLE
Bumping up version of the languageflow dependency

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#231]
Hi, I've noticed that `languageflow` 1.1.9 has been released for some time, but the version of the `languageflow` dependency in `underthesea` is still pinned at 1.1.9a1. I'm wondering that is there any reason for this?

**Comment by rain1024** [comment]
Thank you so much for pointing it out. I will update version of languageflow in underthesea dependencies soon.

**Comment by rain1024** [comment]
@BLKSerene In the version 1.1.16, languageflow version is updated. Please check it out.

**Comment by BLKSerene** [comment]
Thanks!

**Comment by BLKSerene** [comment]
Hi, the latest version of languageflow is 1.1.13, but the version number of languageflow dependency is still pinned at 1.1.13a1, do you have any plan to update it?

And I guess that using 'languageflow>=1.1.13' in setup.py would be better?
