### ISSUE TITLE
Thêm tính năng nhận diện ngôn ngữ 

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#233]
Thêm tính năng nhận diện ngôn ngữ 

Đề xuất 

```
from underthesea import lang_detect

lang_detect("Toàn cảnh con đường dọc sông Tô Lịch chỉ để đi bộ, đi xe đạp")
# vi

lang_detect("The college admissions scandal is more proof that helicopter parenting hurts kids")
# en
```

**Comment by kienvht** [comment]
Với những câu có cả tiếng anh và việt (nhập nhằng) thì sẽ detect như nào hả anh. Ví dụ vài câu bóng đá:
Cầu thủ David Degea hiện đang thi đấu cho câu lạc bộ Manchester United.

**Comment by rain1024** [comment]
@kienvht Cái đấy anh cũng chưa biết. Có 2 lựa chọn (1) Đầu ra là ngôn ngữ xuất hiện nhiều nhất trong câu (2) Tất cả các ngôn ngữ xuất hiện trong câu

Nếu theo (1) thì kết quả của câu trên là vi 
Nếu theo (2) thì kết quả của câu trên là vi, en 

Em nghĩ sao?

**Comment by qhuy4119** [comment]
> Với những câu có cả tiếng anh và việt (nhập nhằng) thì sẽ detect như nào hả anh. Ví dụ vài câu bóng đá:
> Cầu thủ David Degea hiện đang thi đấu cho câu lạc bộ Manchester United.

In my opinion, we can display all the languages in the text with a ranking accounting for how much each language is used in the text, in stead of an arbitrary order

**Comment by rain1024** [comment]
We support this feature from underthesea version 7.0.0

Now you can use `lang_detect` function from underthesea

```python
>>> from underthesea import lang_detect

>>> lang_detect("Cựu binh Mỹ trả nhật ký nhẹ lòng khi thấy cuộc sống hòa bình tại Việt Nam")
vi
```
