### ISSUE TITLE
Lỗi tách câu

### ISSUE THREAD

**Issue by nvlong198** [undertheseanlp/underthesea#237]
**input** = Cầu thủ Duy Mạnh rất chăm mua đồ hiệu tặng bạn gái.Dựa vào việc Quỳnh Anh tag bạn trai Duy Mạnh vào bức hình, có thể khẳng định rằng đây là món quà mà chàng tuyển thủ dành tặng cho cô bạn gái xinh đẹp. Tuy nhiên, cả chiếc Classic Flap và Gabrielle đều đã được Quỳnh Anh sở hữu từ trước đó nên dễ đoán
**output** = ['Cầu thủ Duy Mạnh rất chăm mua đồ hiệu tặng bạn gái.Dựa vào việc Quỳnh Anh tag bạn trai Duy Mạnh vào bức hình, có thể khẳng định rằng đây là món quà mà chàng tuyển thủ dành tặng cho cô bạn gái xinh đẹp.', 'Tuy nhiên, cả chiếc Classic Flap và Gabrielle đều đã được Quỳnh Anh sở hữu từ trước đó nên dễ đoán']
**expect** = ['Cầu thủ Duy Mạnh rất chăm mua đồ hiệu tặng bạn gái.','Dựa vào việc Quỳnh Anh tag bạn trai Duy Mạnh vào bức hình, có thể khẳng định rằng đây là món quà mà chàng tuyển thủ dành tặng cho cô bạn gái xinh đẹp.', 'Tuy nhiên, cả chiếc Classic Flap và Gabrielle đều đã được Quỳnh Anh sở hữu từ trước đó nên dễ đoán']

**Comment by rain1024** [comment]
Câu này tách sai do từ `Dựa` không có dấu cách ở trước. Việc này có thể giải quyết bằng cách thực hiện tokenize trước khi tách câu? 

Liệu đây có phải là một giải pháp tốt?

**Comment by nvlong198** [comment]
Hợp lý, có thể tokenize trước rồi xác định end_of_sentence.
