### ISSUE TITLE
Lỗi Text Classification

### ISSUE THREAD

**Issue by hieuhoang1996** [undertheseanlp/underthesea#238]
classify('Lúc này, tàu kiểm ngư Việt Nam buộc phải tăng tốc, khép gọng kìm, phun vòi rồng để đẩy đuổi hai tàu cá treo cờ Trung Quốc')
--> IndexError: list index out of range

Truyền vào bất kỳ text nào đều lỗi

**Comment by rain1024** [comment]
@hieuhoang1996 Bạn cài đặt underthesea phiên bản mấy?

Bạn đã cài đặt các dependencies và tải pre-trained model như theo hướng dẫn này chưa https://github.com/undertheseanlp/underthesea#6-text-classification ?

**Comment by rain1024** [comment]
@hieuhoang1996 Mình vừa thử nghiệm với underthesea v1.1.15

```
$ pip install Cython
$ pip install joblib future scipy numpy scikit-learn
$ pip install -U fasttext --no-cache-dir --no-deps --force-reinstall
$ underthesea data

$ python
>>> from underthesea import classify
>>> classify('Lúc này, tàu kiểm ngư Việt Nam buộc phải tăng tốc, khép gọng kìm, phun vòi rồng để đẩy đuổi hai tàu cá treo cờ Trung Quốc')
['Chinh tri Xa hoi']
```

**Comment by hieuhoang1996** [comment]
Mình dùng 1.1.15. Mình đã cài hết theo hướng dẫn

`C:\Windows\System32>pip install Cython
Requirement already satisfied: Cython in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (0.29.6)

C:\Windows\System32>pip install joblib future scipy numpy scikit-learn
Requirement already satisfied: joblib in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (0.13.2)
Requirement already satisfied: future in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (0.17.1)
Requirement already satisfied: scipy in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (1.2.1)
Requirement already satisfied: numpy in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (1.16.2)
Requirement already satisfied: scikit-learn in c:\users\thokaka\appdata\local\programs\python\python36\lib\site-packages (0.19.2)

C:\Windows\System32>pip install -U fasttext --no-cache-dir --no-deps --force-reinstall
Collecting fasttext
  Downloading https://files.pythonhosted.org/packages/a4/86/ff826211bc9e28d4c371668b30b4b2c38a09127e5e73017b1c0cd52f9dfa/fasttext-0.8.3.tar.gz (73kB)
    100% |████████████████████████████████| 81kB 556kB/s
Installing collected packages: fasttext
  Found existing installation: fasttext 0.8.3
    Uninstalling fasttext-0.8.3:
      Successfully uninstalled fasttext-0.8.3
  Running setup.py install for fasttext ... done
Successfully installed fasttext-0.8.3

C:\Windows\System32>underthesea data
Component 'classification.fasttext.model' is already existed.

C:\Windows\System32>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from underthesea import classify
>>> classify('Lúc này, tàu kiểm ngư Việt Nam buộc phải tăng tốc, khép gọng kìm, phun vòi rồng để đẩy đuổi hai tàu cá treo cờ Trung Quốc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Thokaka\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\__init__.py", line 43, in classify
    return clf.predict(X)
  File "C:\Users\Thokaka\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 73, in predict
    y_pred = [self.tranform_output(item) for item in y_pred]
  File "C:\Users\Thokaka\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 73, in <listcomp>
    y_pred = [self.tranform_output(item) for item in y_pred]
  File "C:\Users\Thokaka\AppData\Local\Programs\Python\Python36\lib\site-packages\underthesea\classification\model_fasttext.py", line 66, in tranform_output
    y = y[0].replace("__label__", "")
IndexError: list index out of range`

**Comment by rain1024** [comment]
@hieuhoang1996 Có thể đây là lỗi do fasttext không tương thích với Windows. Bạn thử trên ubuntu xem
