### ISSUE TITLE
Lỗi khi test classify trên windows

### ISSUE THREAD

**Issue by hunglsxx** [undertheseanlp/underthesea#245]
![csf](https://user-images.githubusercontent.com/50700597/57846353-3a98c600-77fe-11e9-8453-5fff59457006.PNG)
Mình chạy thử theo docs, cài đặt mọi thứ ok trên windows, nhưng run example nó ra lỗi này.
Mọi người có thể giúp đỡ không ạ?
From newbie with love!

**Comment by rain1024** [comment]
Hiện tại, underthesea không hỗ trợ Windows bạn nhé.

Bạn thử lại trên Ubuntu hay CentOS xem.

Chúc bạn thành công
