### ISSUE TITLE
Hỗ trợ các ký tự emoji 

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#247]
Hỗ trợ các ký tự emoji 

Issue liên quan: https://github.com/trungtv/vivi_spacy/issues/4

Hiện tại underthesea v1.1.15 vẫn tách các ký tự emoji 

```
>>> from underthesea import word_tokenize
>>> word_tokenize("Tầm giá quá rẻ để mua 1 cục bực tức để trên người :))")
[
  'Tầm', 'giá', 'quá', 'rẻ', 'để', 'mua', '1', 'cục', 'bực tức', 'để', 'trên', 'người',
  ':', ')', ')'
]
```

Expected 

```
>>> from underthesea import word_tokenize
>>> word_tokenize("Tầm giá quá rẻ để mua 1 cục bực tức để trên người :))")
[
  'Tầm', 'giá', 'quá', 'rẻ', 'để', 'mua', '1', 'cục', 'bực tức', 'để', 'trên', 'người',
  ':))'
]
```

**Comment by ttran1904** [comment]
Same, too. I am running some LDA model and is hoping to only deal with word characters (because my project expects to output top words from documents). However, it is difficult to extract emojis out of the text although I used underthesea word_tokenize.

**Comment by rain1024** [comment]
@ttran1904 In the latest version of underthesea (v1.1.2a0), I create some [regular expressions](https://github.com/undertheseanlp/underthesea/blob/master/underthesea/word_tokenize/regex_tokenize.py#L109) for handling emoji. Please check it and give me some feedback. Thank you

To test it, try these code

```
$ pip install underthesea==1.2.2a0
```

```
>>> from underthesea import word_tokenize
>>> text = "Một vài ký tự emoji <3 :D"
>>> word_tokenize(text)
['Một vài', 'ký', 'tự', 'emoji', '<3', ':D']
```
