### ISSUE TITLE
New option for word_tokenize

### ISSUE THREAD

**Issue by lhdung258** [undertheseanlp/underthesea#248]
word_tokenize works really great! But can you add the additional option for the join character indicates how to form a word.

- Input:
1. `word_tokenizer('Thầy giáo dạy rất giỏi', format='text', join=' ')`
2. `word_tokenizer('Thầy giáo dạy rất giỏi', format='text', join='_')`
- Expected output:
1. Thầy giáo dạy rất giỏi
2. Thầy_giáo dạy rất giỏi

Because I find it useful to use word_tokenizer to tokenize punctuation correctly, but not really want to tokenize the word

**Comment by rain1024** [comment]
If your requirement is tokenize `tokens` (not tokenize `words`), you can use `tokenize` function. It meets your need and a lot faster than `word_tokenize` function

```
>>> from underthesea.word_tokenize.regex_tokenize import tokenize
>>>  tokenize('Thầy giáo dạy rất giỏi')
['Thầy', 'giáo', 'dạy', 'rất', 'giỏi']
```
