### ISSUE TITLE
Lỗi OS

### ISSUE THREAD

**Issue by hieuthehungry** [undertheseanlp/underthesea#265]
Mình đang download tc_general thì gặp lỗi sau:
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\H\\.underthesea\\models\\tc_svm_vntc_20190607.zip?dl=1'
Mọi người chỉ cho mình cách xử lý với, thanks

**Comment by QuangPHG** [comment]
Chào bạn, phiên bản hiện tại của underthesea chưa hỗ trợ đối với Windows. Nhóm sẽ xem xét và cập nhật phần hỗ trợ Windows trong các phiên bản sau. Trước đó, bạn có thể sử dụng underthesea trên Unbuntu nhé.

**Comment by hieuthehungry** [comment]
Vâng ạ, thôi mình tìm cách tự build phần này vậy
