### ISSUE TITLE
Hỏi về underthesea-flow

### ISSUE THREAD

**Issue by thanhquang20297** [undertheseanlp/underthesea#266]
Dạ em có tham khảo vài project về name entity thì thấy các anh chị có sử dụng underthesea-flow khi import. Nhưng khi em thử cài đặt pip3 install underthesea_flow thì không được. Em tìm hiểu trên web thì gặp 1 link source để down về nhưng link này cũng đã die. Anh chị có thể giúp em được không ạ. Em xin cảm ơn

**Comment by rain1024** [comment]
> Dạ em có tham khảo vài project về name entity thì thấy các anh chị có sử dụng underthesea-flow khi import.

Hi @thanhquang20297, project nào sử dụng underthesea-flow nhỉ? Em có thể đưa link tương ứng đến các project đấy không?

> Nhưng khi em thử cài đặt pip3 install underthesea_flow thì không được.

Hiện tại thì không có package `underthesea_flow` em nhé, hay em nhầm với `languageflow`?

**Comment by thanhquang20297** [comment]
Dạ do này là source em tham khảo nên em không dám public ạ, nhưng em xin code 1 đoạn code nhỏ.

Em cũng có tìm hiểu thì được biết mình từng có sử dụng (Page 5/Chapter 2): [https://buildmedia.readthedocs.org/media/pdf/languageflow-bna/latest/languageflow-bna.pdf](url)

```
from os.path import dirname, join
from underthesea_flow.flow import Flow
from underthesea_flow.model import Model
from underthesea_flow.model.crf import CRF
from underthesea_flow.transformer.tagged import TaggedTransformer
from underthesea_flow.validation.validation import TrainTestSplitValidation

from preprocess import vlsp2016

if __name__ == '__main__':
    # =====#
    # Start an experiment with flow
    # =====#
    flow = Flow()
    flow.log_folder = join(dirname(__file__), "logs")
```

**Comment by rain1024** [comment]
> Dạ do này là source em tham khảo nên em không dám public ạ, nhưng em xin code 1 đoạn code nhỏ.

Project này là từ khá lâu rồi. Hiện tại nhóm không sử dụng module này nữa, mà chuyển qua module [languageflow](https://github.com/undertheseanlp/languageflow) em nhé

**Comment by thanhquang20297** [comment]
Dạ vậy mình có source nào khác để tham khảo không ạ? Em có thử tìm hiểu [https://github.com/undertheseanlp/ner](url) nhưng không apply được.
