### ISSUE TITLE
ModuleNotFoundError: No module named 'fastText'

### ISSUE THREAD

**Issue by hieplt1018** [undertheseanlp/underthesea#268]
Em đã chạy "pip install git+https://github.com/facebookresearch/fastText.git" 
mà vẫn bị lỗi no module named fastText anh ạ.
Và câu lệnh underthesea data cũng không còn nữa anh ạ.

**Comment by rain1024** [comment]
Hi @hieplt1018 



> Em đã chạy "pip install git+https://github.com/facebookresearch/fastText.git"
mà vẫn bị lỗi no module named fastText anh ạ.

fasttext vừa update version, để cài fasttext em sử dụng câu lệnh sau:

```
pip install git+https://github.com/facebookresearch/fastText@6dd2e11b5fe82854c4529d2a58d699b2cb182b1b
```

Sau đó em download mô hình và sử dụng hàm predict theo hướng dẫn [link](https://github.com/undertheseanlp/underthesea#6-text-classification)

Cài đặt dependencies và tải các mô hình 

```
$ pip install git+https://github.com/facebookresearch/fastText@6dd2e11b5fe82854c4529d2a58d699b2cb182b1b
$ pip install unidecode
$ underthesea download tc_general
$ underthesea download tc_bank
```
Sử dụng hàm `classify` để phân loại văn bản

```
>>> # -*- coding: utf-8 -*-
>>> from underthesea import classify

>>> classify('HLV đầu tiên ở Premier League bị sa thải sau 4 vòng đấu')
['The thao']
>>> classify('Hội đồng tư vấn kinh doanh Asean vinh danh giải thưởng quốc tế')
['Kinh doanh']

>> classify('Lãi suất từ BIDV rất ưu đãi', domain='bank')
['INTEREST_RATE']
```

> Và câu lệnh underthesea data cũng không còn nữa anh ạ.

Câu lệnh `underthesea data` được thay thế bằng câu lệnh `underthesea download [MODEL_NAME]` em nhé

**Comment by hieplt1018** [comment]
Chay ok roi anh a.
