### ISSUE TITLE
Lỗi Sentiment Analysis

### ISSUE THREAD

**Issue by hieplt1018** [undertheseanlp/underthesea#269]
Anh ơi, phần Sentiment khi run bị lỗi "module 'text_feature' has no attribute 'RemoveDuplicate' ạ

**Comment by rain1024** [comment]
@hieplt1018 Em chạy câu lệnh như thế nào ?

**Comment by hieplt1018** [comment]
Em chạy lại theo hướng dẫn và được rồi anh ạ. Em cảm ơn anh/
