### ISSUE TITLE
performance of word segmentation is not good

### ISSUE THREAD

**Issue by TQuy** [undertheseanlp/underthesea#270]
I like the features of your word segmentation, and prefer it over pyvi or RDRsegmenter . However, its performance is not good, it cannot even segment `hà nội` as  a single token given the text 

> tính cho tôi phí giao 2 kg hàng từ vinh ra hà nội
or 

> hà nội cách có xa đây không

However, It can when I replace "hà nội" with "Hà Nội"

**Comment by rain1024** [comment]
Thanks for your feedback. The reason is current model was trained in dataset which is case sensitive. So "Hà Nội" and "hà nội" is different. 

Do you have any idea to improve it?

**Comment by TQuy** [comment]
if we use word embedding trained from skip-gram, I guess we can lower all the words in preprocessing and add features such as capitalized, all-digits into each word's embedding vector

**Comment by rain1024** [comment]
yeah. I'm considering apply neural networks in underthesea. But it's far from release now. 

Can you do some experiment with your idea? Never forget merge request is always welcome  :ok_hand:

**Comment by TQuy** [comment]
It's really hard without the data

**Comment by rain1024** [comment]
@TQuy Please inbox in [Underthesea Fanpage](https://www.facebook.com/undertheseanlp/) or email me undertheseanlp@gmail.com for further discussion about training data for this task
