### ISSUE TITLE
POS tagging chưa chính xác

### ISSUE THREAD

**Issue by TechMaster** [undertheseanlp/underthesea#271]
Chức năng POS tagging khá ổn, thỉnh thoảng có những lỗi nhỏ như thế này. Làm sao để cộng đồng có thể contribute fix bug được tác giả ơi?
![image](https://user-images.githubusercontent.com/1491686/61530244-bb1db200-aa4d-11e9-9819-62aef61da363.png)

**Comment by rain1024** [comment]
Câu hỏi này hay quá anh ạ. Em sẽ cho lên fanpage của underthesea để mọi người cùng thảo luận

**Comment by rain1024** [comment]
Anh ơi, anh có thể cải tiến bộ dữ liệu huấn luyện bằng cách tạo issue ở đây anh nhé 

https://github.com/undertheseanlp/resources/issues

**Comment by TechMaster** [comment]
hôm nào gặp nhau bàn vụ làm chatbot đi. Team mình đang build chatbot. Rất
cần chuyên gia join team tư vấn

**Comment by rain1024** [comment]
@TechMaster 

> hôm nào gặp nhau bàn vụ làm chatbot đi
vụ này nằm ngoài scope của issue này ạ
