### ISSUE TITLE
Sử dụng underthesea để gán nhãn do người dùng tự tạo

### ISSUE THREAD

**Issue by NguyenNamUET** [undertheseanlp/underthesea#272]
Chào các anh,
Em đã cài đặt underthesea NER theo hướng dẫn tại https://github.com/undertheseanlp/ner trên Linux. Tuy nhiên, em muốn sử dụng underthesea để gán nhãn do người dùng tự tạo. thì underthesea có hỗ trợ chức năng này không? Nếu có thì sử dụng chức năng trên như thế nào?

**Comment by rain1024** [comment]
@NguyenNamUET 

Để gán nhãn do người dùng tự tạo, em cần tạo lại làm ba bước 

1. Tạo bộ dữ liệu huấn luyện (trong đó có các câu có chứa nhãn tự tạo)
2. Huấn luyện lại mô hình với bộ dữ liệu mới
3. Viết lại hàm ner, sử dụng mô hình vừa huấn luyện để gán nhãn cho các câu mới

**Comment by NguyenNamUET** [comment]
Bộ dữ liệu huấn luyện thì sẽ sử dụng format nào vậy anh?

**Comment by rain1024** [comment]
Bộ dữ liệu sử dụng theo định dạng của [CoNLL](https://universaldependencies.org/docs/format.html) em nhé
