### ISSUE TITLE
Is `word_tokenize` a subset of `chunk`?

### ISSUE THREAD

**Issue by foolip** [undertheseanlp/underthesea#273]
Language enthusiast and Vietnamese novice here. Playing around with underthesea a bit:
```
>>> s = 'Không ngừng sáng tạo, phấn đấu tạo ra những sản phẩm và dịch vụ chất lượng cao với giá cạnh tranh.'
>>> word_tokenize(s)
['Không', 'ngừng', 'sáng tạo', ',', 'phấn đấu', 'tạo', 'ra', 'những', 'sản phẩm', 'và', 'dịch vụ', 'chất lượng', 'cao', 'với', 'giá', 'cạnh tranh', '.']
>>> [x[0] for x in chunk(s)] == word_tokenize(s)
True
```

So, I wonder if `word_tokenize` is internally the same as `chunk` but throws away some information?

Background: I'd like to make a list of common Vietnamese words, and thought I'd try processing the ~27k .vn sites in https://httparchive.org/. Perhaps underthesea already effectively has word frequency information that I could use directly?

**Comment by rain1024** [comment]
Hi @foolip 

Sorry for my late reply. 

> So, I wonder if word_tokenize is internally the same as chunk but throws away some information?

The purpose of `chunk` is detect noun phrases and verb phrases in sentence, such as 

```
>>> s = 'Chủ tịch Quốc hội: Dẹp bỏ những quỹ tài chính “thu nhiều, chi không bao nhiêu'
>>> word_tokenize(s)
['Chủ tịch', 'Quốc hội', ':', 'Dẹp bỏ', 'những', 'quỹ', 'tài chính',  '“', 'thu', 'nhiều', ',', 'chi', 'không', 'bao nhiêu']
>>> chunk(s) # expected
['Chủ tịch Quốc hội', ':', 'Dẹp bỏ', 'những', 'quỹ tài chính',  '“', 'thu', 'nhiều', ',', 'chi', 'không', 'bao nhiêu']
```

So, `chunk` will detect two noun phrases in this sentence: *Chủ tịch Quốc hội* (President of Congress) and *quỹ tài chính* (financial fund)

However, `chunk` in underthesea still not good enough to detect this phrases.

>  I'd like to make a list of common Vietnamese words ... Perhaps underthesea already effectively has word frequency information that I could use directly?

We hasn't made this analysis. Can you do it and share what you find interesting

**Comment by foolip** [comment]
Thanks @rain1024, it sounds like for my purposes `word_tokenize` is the most appropriate, even though grouping larger noun phrases would be interesting in a frequency analysis. I could try both, now that I know they're not identical.

Since there's nothing actionable for this project in this issue, I'll go ahead and close it.
