### ISSUE TITLE
underthesea docker?

### ISSUE THREAD

**Issue by nguyenkaos** [undertheseanlp/underthesea#275]
Hello team, xin hỏi dự án mình có docker sẵn không nhỉ? nế có cho mình xin nhé. Thanks team!

**Comment by rain1024** [comment]
@nguyenkaos hiện tại underthesea chưa có docker bạn nhé

**Comment by rain1024** [comment]
[Cập nhật trạng thái] Hiện tại, mình đang build thử image cho underthesea sử dụng tính năng [Github Packages](https://github.com/features/packages)

Thử nghiệm

```
docker run docker.pkg.github.com/undertheseanlp/underthesea/app:0.1.alpha
```

**Comment by rain1024** [comment]
View related issue #705
