### ISSUE TITLE
Smarter version numbers for dependencies of Underthesea

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#276]
Hi, the latest version of NLTK is 3.4.4, which is a dependency required by Underthesea, but the version of NLTK is pinned at 3.4. To minimize the maintenance workl, I suggest using a smarter version number for the NLTK dependency:
```
install_requires = [
    'Click>=6.0',
    'python-crfsuite==0.9.6',
    'nltk>=3.4,<3.5',
    'languageflow==1.1.13a1'
]
```

**Comment by rain1024** [comment]
thanks for your suggestion. I will update it in next release
