### ISSUE TITLE
Minimizing dependency requirements for Underthesea

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#277]
`python-crfsuite` is not used anywhere inside `Underthesea`, so it should be removed from the dependency requirements.

**Comment by rain1024** [comment]
@BLKSerene I use `pycrfsuite` from `python-crfsuite` here 

https://github.com/undertheseanlp/underthesea/blob/master/underthesea/word_tokenize/model.py#L3

**Comment by BLKSerene** [comment]
Okay, I see. Sorry for having missed that.
