### ISSUE TITLE
Cập nhật phiên bản fasttext 0.9.1

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#279]
Hiện tại, fasttext đã ra phiên bản mới 0.9.1.

Gây ra lỗi import

```
======================================================================
ERROR: test_classify_simple_case (tests.classification.test_bank.TestClassify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/undertheseanlp/underthesea/tests/classification/test_bank.py", line 9, in test_classify_simple_case
    actual = classify(text, domain='bank')
  File "/home/travis/build/undertheseanlp/underthesea/underthesea/classification/__init__.py", line 26, in classify
    from underthesea.classification import bank
  File "/home/travis/build/undertheseanlp/underthesea/underthesea/classification/bank/__init__.py", line 7, in <module>
    from languageflow.models.text_classifier import TextClassifier
  File "/home/travis/build/undertheseanlp/underthesea/.tox/py36/lib/python3.6/site-packages/languageflow/models/text_classifier.py", line 4, in <module>
    import fastText
ModuleNotFoundError: No module named 'fastText'
```

**Comment by rain1024** [comment]
Trong phiên bản tiếp theo, cần cập nhật fasttext lên 0.9.1

**Comment by longtv02** [comment]
> Hiện tại, fasttext đã ra phiên bản mới 0.9.1.
> 
> Gây ra lỗi import
> 
> ```
> ======================================================================
> ERROR: test_classify_simple_case (tests.classification.test_bank.TestClassify)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/home/travis/build/undertheseanlp/underthesea/tests/classification/test_bank.py", line 9, in test_classify_simple_case
>     actual = classify(text, domain='bank')
>   File "/home/travis/build/undertheseanlp/underthesea/underthesea/classification/__init__.py", line 26, in classify
>     from underthesea.classification import bank
>   File "/home/travis/build/undertheseanlp/underthesea/underthesea/classification/bank/__init__.py", line 7, in <module>
>     from languageflow.models.text_classifier import TextClassifier
>   File "/home/travis/build/undertheseanlp/underthesea/.tox/py36/lib/python3.6/site-packages/languageflow/models/text_classifier.py", line 4, in <module>
>     import fastText
> ModuleNotFoundError: No module named 'fastText'
> ```

Có ai biết cách fix lỗi này không? Lọ mọ cả ngày mà vẫn chưa ra :(

**Comment by rain1024** [comment]
@longtv02 Trong phiên bản mới nhất `v1.1.17`, lỗi này được fix rồi chứ nhỉ?
