### ISSUE TITLE
 API integration

### ISSUE THREAD

**Issue by seakBz** [undertheseanlp/underthesea#287]
Mình muốn sử dụng Chatbot này trên nền tảng node js với project của mình [Chat-bot-facebook](https://github.com/seakBz/chatbot/)
Hiện tại mình đang sử dụng API của trang web bên bạn
![img](https://i.imgur.com/xifpkMm.png)

Bên bạn có thể cung cấp module sử dụng đc trên node js hoặc có thể tạo API để mọi người sử dụng được k ?

**Comment by rain1024** [comment]
@seakBz 

> Hiện tại mình đang sử dụng API của trang web bên bạn ...  tạo API để mọi người sử dụng
Bạn đang sử dụng API của chatbot rồi mà nhỉ? Sao lại cần API nữa làm gì

**Comment by seakBz** [comment]
> @rain1024
> 
> Bạn đang sử dụng API của từ web service của chatbot rồi, sao lại cần API nữa làm gì nhỉ?
> >
Mình muốn xin phép bạn để dùng API này. Ban đầu mình nghĩ trang web kia chỉ là bạn deploy dùng để demo nên muốn hỏi nếu request nhiều có vấn đề gì không?

**Comment by rain1024** [comment]
@seakBz Không vấn đề gì bạn nhé. good luck
