### ISSUE TITLE
Bumping up version of the languageflow dependency

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#289]
Hi, the latest version of `languageflow` is 1.1.13, but the version number of `languageflow` dependency is still pinned at 1.1.13a1, do you have any plan to update it?

And I guess that using 'languageflow>=1.1.13' in `setup.py` would be better?

**Comment by rain1024** [comment]
@BLKSerene thanks for your support.

I think we should reopen last issue #231 to discuss about dependency problem rather open a new once. Please re-post your suggestion in #231. Thank you

Duplicate #231

**Comment by BLKSerene** [comment]
Okay.
