### ISSUE TITLE
word_tokenize chưa train và regex các loại , biển số xe ,v..v...

### ISSUE THREAD

**Issue by microvnn** [undertheseanlp/underthesea#290]
- Tiêm kích **F-16** Bỉ bám sát, dùng cảm biến ảnh nhiệt để chụp ảnh tiêm kích bom **Su-34** Nga trên không phận quốc tế ở biển Baltic
- ông đến quán Downtime dự **Actors' Hour** - chương trình dành cho các nghệ sĩ
- Tai nạn, do tài xế điều khiển xe Lexus biển kiểm soát **49X-6666** khiến 4 người tử vong và 6 người bị thương nặng
- BMW đã phát triển **_Rolls-Royce_** như thế nào
- Tàu **Apolo-2** ,...
- Đoàn tàu **SE-4**...
- **do Phó chủ tịch Bùi Đức Hinh ký .** VÀ **do Phó chủ tịch Bùi Đức Hinh ký** dư hoạc thiếu dấu . kết quả hoàn toàn khác nhau :) <-- rất nhiều trường hợp bị như vậy có punct vào là nó khác ngay.

**Comment by rain1024** [comment]
thanks @microvnn đã report lỗi.

Bạn có thể gửi một vài merge request fix một vài trường hợp phổ biến không?

**Comment by microvnn** [comment]
https://docs.google.com/spreadsheets/d/1rtvAExDzy-vHY8p_9i_eEhZ6xM_XT99PDLcu7viPwMg/edit?usp=sharing

Dear.

**Comment by rain1024** [comment]
@microvnn Wow. Thanks bạn đưa ra rất nhiều trường hợp hay.

Bạn có thể contribute trực tiếp vào code của underthesea rồi gửi merge request không?

https://github.com/undertheseanlp/underthesea/blob/master/underthesea/word_tokenize/regex_tokenize.py

**Comment by microvnn** [comment]
Việt Nam luôn nhập các ký tự **oà òa**, **oè òe** đều đúng cho nên cần verify hết thành chuẩn :
ví dụ: òa ->oà hết để tokenlizer cho đồng nhất

**Comment by rain1024** [comment]
@microvnn Hôm nay mình mới invest vào issue này một chút. 

Mới phát hiện ra các case bạn đưa ra như `F-16`, `Apolo-2`, `Rolls-Royce` đều có thể "gộp" vào một token với regex đơn giản 

```
pattern = r"\w+\-\w+"
```

Nhưng các case này cũng conflict với các case cần tách như `Moscow-Washington`, `2010-2015`

Hiện tại mình cũng chưa nghĩ ra cách nào để xử lý việc tokenize bằng regex cả ?
