### ISSUE TITLE
word_tokenize tokenize với dấu câu.

### ISSUE THREAD

**Issue by nguyenvanhieuvn** [undertheseanlp/underthesea#291]
Em có thử với một số câu khác thì hình như chỉ các câu có Canxi sau dấu chấm bị

```
>>> str = 'Quá đúng . Canxi là một trong những khoáng chất'
>>> str = underthesea.word_tokenize(text, format='text')
>>> print(str)
Quá đúng ._Canxi là một trong những khoáng_chất
```

**Comment by rain1024** [comment]
@nguyenvanhieuvn Thanks em đã report. Lỗi này có thể walk through bằng cách tách câu trước. 

Nhóm sẽ cải tiến ở các lần release sau

**Comment by rain1024** [comment]
same as #536
