### ISSUE TITLE
word_tokenize thủ công?

### ISSUE THREAD

**Issue by iamtung** [undertheseanlp/underthesea#292]
Chào mọi người,

Mình muốn hỏi là trong trường hợp mình thấy word_tokenize chưa chính xác và muốn chỉnh sửa dữ liệu tokenize thì có cách nào làm thủ công không ạ? Ví dụ: chữ Việt Nam bị tách thành 2 word khác nhau ['Việt', 'Nam'], giờ mình muốn định nghĩ để lần sau tiến hành word_tokenize có thể xác định chữ Việt Nam là 1 từ ['Việt Nam'].

Cảm ơn mọi người,

**Comment by rain1024** [comment]
@iamtung Bạn có thể sử dụng underthesea cho một tập văn bản đủ nhiều, sau đó thống kê các lỗi phổ biến (ví dụ một lỗi là chữ "Việt Nam" bị tách thành 2 word khác nhau "Việt", "Nam")

Đến đây có 2 hướng giải quyết

Phương án 1:  Bạn tìm các câu bị lỗi, **gán nhãn lại**, sau đó **thêm vào tập huấn luyện**, và **huấn luyện lại mô hình** (bạn có thể tham khảo project [word_tokenize](http://github.com/undertheseanlp/word_tokenize) của underthesea) 

Phương án 2: Bạn có thể thêm phần **hậu xử lý**, để nếu gặp lỗi thì sửa lại 

Trong ví dụ "Việt Nam" bị tách thành 2 word "Việt", "Nam", một cách đơn giản như sau:

```
1. Khởi tạo một tập từ mà underthesea có thể tách sai (theo thống kê lúc đầu)
2. Duyệt toàn bộ các tokens trong câu
  Với mỗi token, tạo các từ bằng cách ghép token này với các token tiếp theo
  Kiểm tra các từ này có thuộc tập từ kể trên không
     Nếu có, nối các token này lại với nhau
```

Chúc bạn thành công :D

**Comment by iamtung** [comment]
Thank bạn nhiều, mình đã hiểu rồi :D
