### ISSUE TITLE
Thêm từ khóa địa lý cụ thể vào data

### ISSUE THREAD

**Issue by tagmetag** [undertheseanlp/underthesea#293]
Chào bạn,

Mình rất thích và đánh giá cao thư viện này và đang sử dụng cho dự án của mình tính năng tách từ. Mình muốn thêm các từ địa lý cụ thể để có thể tách từ chính xác hơn. Ở đây từ địa lý là "phú quốc" khi viết thường thì không tác được mà viết hoa mới tách được. Làm thế nào để xử lý việc này.

<img width="770" alt="Screen Shot 2020-01-08 at 23 32 38" src="https://user-images.githubusercontent.com/19923843/71996669-29aa3280-326f-11ea-8341-807b7b856927.png">

Xin cảm ơn

**Comment by rain1024** [comment]
@tagmetag Cảm ơn bạn đã quan tâm đến thư viện underthesea :D

Câu hỏi này đã được thảo luận, bạn tham khảo issue #292 nhé.

Thanks

**Comment by tagmetag** [comment]
Cảm ơn bạn, đúng cái mình cần. Mình đang hóng tính năng tự động sửa lỗi chính tả, thêm dấu + tách từ không dấu. Hy vọng sắp tới Underthesea sẽ ra mắt.

Chúc team 1 năm thành công
