### ISSUE TITLE
I-LOC đứng một mình

### ISSUE THREAD

**Issue by duongkstn** [undertheseanlp/underthesea#297]
Mình input câu "Nhà tôi ở Phường Dịch Vọng, Cầu Giấy" và dùng ner thì được kết quả:
'Nhà': 'O',
'tôi': 'O',
'ở': 'O',
'Phường': 'B-LOC',
'Dịch Vọng': 'B-LOC',
',': 'O',
'Cầu Giấy': 'I-LOC'

Mình thắc mắc là token 'Cầu Giấy' gán là 'I-LOC' là vô lý vì nhãn loại 'I-...' không thể đứng một mình vậy được, trước đó phải là một nhãn 'I-LOC' hoặc 'B-LOC' khác. Mong nhóm xem xét

**Comment by rain1024** [comment]
> Mình input câu "Nhà tôi ở Phường Dịch Vọng, Cầu Giấy" và dùng ner thì được kết quả:
> 'Nhà': 'O',
> 'tôi': 'O',
> 'ở': 'O',
> 'Phường': 'B-LOC',
> 'Dịch Vọng': 'B-LOC',
> ',': 'O',
> 'Cầu Giấy': 'I-LOC'

Mình đã thử lại và đúng là hiện tại module ner đang gặp lỗi này. 

> Mình thắc mắc là token 'Cầu Giấy' gán là 'I-LOC' là vô lý vì nhãn loại 'I-...' không thể đứng một mình vậy được, trước đó phải là một nhãn 'I-LOC' hoặc 'B-LOC' khác. Mong nhóm xem xét

Lỗi này đúng là lạ thật. Nhóm mình sẽ xem xét và fix lỗi này trong những release tiếp theo nhé. Cảm ơn @duongkstn

**Comment by rain1024** [comment]
Trùng với #288
