### ISSUE TITLE
ImportError: cannot import name 'word_tokenize'

### ISSUE THREAD

**Issue by michaelLampard** [undertheseanlp/underthesea#306]
Chào cả nhà,
Khi sử dụng thư viện underthesea, em gặp phải lỗi 
`ImportError: cannot import name 'word_tokenize'`
Môi trường sử dụng:
- Ubuntu 18.04
- Python 3.6.9 64 bit (trên hệ điều hành có thêm Python 2.7.17)
Mô tả:
- Cài đặt:
`pip3 install underthesea`
- Code:
`from underthesea import word_tokenize`

Cả nhà giúp em tại sao như vậy ạ?
Em xin chân thành cảm ơn!

**Comment by rain1024** [comment]
@michaelLampard em in toàn bộ lỗi ra nhé

**Comment by michaelLampard** [comment]
> @michaelLampard em in toàn bộ lỗi ra nhé
Vâng ạ
Code:
`from underthesea import word_tokenize
sentence = 'Chàng trai 9X Quảng Trị khởi nghiệp từ nấm sò'

tokenized = word_tokenize(sentence, format="text")

print(tokenized)`

Lỗi:
`Traceback (most recent call last):
  File "/home/user/workspaces/NLP/Underthesea/underthesea.py", line 1, in <module>
    from underthesea import word_tokenize
  File "/home/user/workspaces/NLP/Underthesea/underthesea.py", line 1, in <module>
    from underthesea import word_tokenize
ImportError: cannot import name 'word_tokenize'`

**Comment by michaelLampard** [comment]
> @michaelLampard em in toàn bộ lỗi ra nhé

Vâng ạ. 
Code:
`from underthesea import word_tokenize
sentence = 'Chàng trai 9X Quảng Trị khởi nghiệp từ nấm sò'

tokenized = word_tokenize(sentence, format="text")

print(tokenized)`

Lỗi:
Traceback (most recent call last):
  File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in <module>
    from underthesea import word_tokenize
  File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in <module>
    from underthesea import word_tokenize
ImportError: cannot import name 'word_tokenize'
>

**Comment by rain1024** [comment]
> Lỗi:
> Traceback (most recent call last):
> File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in
> from underthesea import word_tokenize
> File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in
> from underthesea import word_tokenize
> ImportError: cannot import name 'word_tokenize'

Em thử đổi tên script thành test_underthesea hay gì đó xem?

**Comment by michaelLampard** [comment]
> @michaelLampard
> 
> > Lỗi:
> > Traceback (most recent call last):
> > File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in
> > from underthesea import word_tokenize
> > File "/home/michael/netcore-workspaces/NLP/VNCoreNLP/underthesea.py", line 1, in
> > from underthesea import word_tokenize
> > ImportError: cannot import name 'word_tokenize'
> 
> Em thử đổi tên file `underthesea.py`trong thư mục `VNCoreNLP` thành `test_underthesea.py` hay gì đó xem, anh nghĩ vấn đề là tên script `underthesea.py` trùng với tên thư viện `underthesea`

Đúng rồi ạ. Em cảm ơn anh!
