### ISSUE TITLE
Too strict dependency specification

### ISSUE THREAD

**Issue by kamo-naoyuki** [undertheseanlp/underthesea#308]
https://github.com/undertheseanlp/underthesea/blob/3eeea869a35383293c2f4247b8cddafbb4f1c9fe/setup.py#L25-L26

Underthesea requires specific version for these modules, but it makes it difficult for this module to coexist with another project because these modules is very major modules and many project requires more upper version.
Why does underthesea require specific version?

**Comment by rain1024** [comment]
Dear @kamo-naoyuki, 

@kamo-naoyuki  We must strict dependencies, in this case is `scikit-learn` and `joblib` because there are some major differences API in `scikit-learn` version `0.19` and `0.20`

However, ideas are always welcomed. Please let us known what is suitable dependencies for you and we will consider to change our specification.

**Comment by kamo-naoyuki** [comment]
If so, it's enough to require scikit-learn==0.20, or >=0.20, isn't it? >=0.20 is better for such case.

**Comment by BLKSerene** [comment]
I strongly agree with @kamo-naoyuki.
I use `underthesea` in my project and there a bunch of dependencies in it. It make me far more difficult to manage the compatibility of these dependencies in this case.

`scikit-learn>=0.20` and `joblib >=0.13.2` would be much much better for me and also easier to handle for later versions of `underthesea` I suppose.
The same for `python-crfsuite` and `nltk`.

**Comment by rain1024** [comment]
@kamo-naoyuki @BLKSerene Today, I updated some dependencies of underthesea and release new version `v1.2.1.a0`

```
install_requires = [
    'Click>=6.0',
    'python-crfsuite>=0.9.6',
    'nltk>=3.4,<3.5',
    'tabulate',
    'tqdm',
    'requests',
    'joblib',
    'scikit-learn>=0.20,<0.22',
    'unidecode'
]
```

Is it better for you? Please give me some feedback. Thanks

**Comment by BLKSerene** [comment]
@rain1024  As per its name, `NLTK` is a natural language toolkit, features are frequently added into it, but there are few removals, unless `NLTK` pump its major version, so I think `'nltk>=3.4, <4.0'` would be more flexible and this will not have any side effects on `Underthesea`.

**Comment by rain1024** [comment]
> @rain1024 As per its name, `NLTK` is a natural language toolkit, features are frequently added into it, but there are few removals, unless `NLTK` pump its major version, so I think `'nltk>=3.4, <4.0'` would be more flexible and this will not have any side effects on `Underthesea`.

I agree. I will remove nltk version to make it more flexible.

> And the latest version of `NLTK` is 3.5, the latest version of `scikit-learn` is 0.23.2, these changes still make `pip` unhappy with dependency compatibilities. Are there any reasons that `scikit-learn` v0.23 is incompatible with `Underthesea`?

The reason is `classify` and `sentiment` models are trained in scikit-learn v0.19. There are some incompatibles in scikit-learn v0.22+ to load these models. I will find some solutions for this issue.

**Comment by BLKSerene** [comment]
@rain1024 If the model was trained on `sklearn` v0.19, is it possible to include the pre-trained models in the package (if the size of the models is not too large, or `Underthesea` could ask the user to download them from Github if necessary) and simply remove this dependency?

**Comment by rain1024** [comment]
@BLKSerene Here is an example of a model

```
~/.underthesea/models/SA_GENERAL$ ls -alh
total 45M
drwxrwxr-x  2 anhv anhv 4,0K Thg 1 28 13:55 .
drwxrwxr-x 10 anhv anhv 4,0K Thg 1 28 13:55 ..
-rw-rw-r--  1 anhv anhv   46 Thg 1 28 13:55 metadata.json
-rw-rw-r--  1 anhv anhv  45M Thg 1 28 13:55 pipeline.joblib
```

The model size is about 40M+, so I don't want to include this to package.

The problem is with sklearn 0.22+, `joblib.load(model_file)` is not working (there are some incompatible API with sklearn 0.19 and sklearn 0.22+). The only solution that I know at the moment is re train `sentiment` models in sklearn 0.22+, it will make it work with sklearn 0.22+.

I will continue researching for further update.
