### ISSUE TITLE
[sentiment bank domain] TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by longtv02** [undertheseanlp/underthesea#310]
<img width="1067" alt="Screen Shot 2020-09-25 at 11 00 00" src="https://user-images.githubusercontent.com/63444660/94225195-8abd8780-ff1e-11ea-8903-9876967d47cb.png">

**Comment by hmhuan** [comment]
Theo hàm trên thì sentence = Sentence(text) (parameter cho labels không có nên mặc định là None)
bên class Sentence có thể thấy được qua constructor __init__
(https://github.com/undertheseanlp/underthesea/blob/3eeea869a35383293c2f4247b8cddafbb4f1c9fe/underthesea/data.py#L40)
Nên cái labels = sentence.labels ra None.

**Comment by rain1024** [comment]
Fixed in commit [#8896fd7](https://github.com/undertheseanlp/underthesea/commit/8896fd74c5d57a4eb7e10239fd3837a561a6ecad)
