### ISSUE TITLE
Giải thích loại từ

### ISSUE THREAD

**Issue by luan123z** [undertheseanlp/underthesea#312]
Hi bạn, bạn có thể giải thích ý nghĩa của các từ viết tắt này ko?  https://prnt.sc/upxryt

**Comment by KO-KMS-AT12** [comment]
N : danh từ
Ny : danh từ viết tắt, vay mượn
Np : danh từ riêng
Nc : loại từ
Nu: kí hiệu đơn vị
M : chữ số, đơn vị đếm (số từ)
P : đại từ
L : từ hạn định
T : trợ từ
V : động từ
A : tính từ
R : trạng từ
C : liên từ phụ thuộc
CC : liên từ kết hợp 
E : giới từ
I : thán từ
CH : kí tự đặc biệt
X : không xác định được

còn 1 số loại nữa mà ít dùng mình k liệt kê.

**Comment by luan123z** [comment]
@KO-KMS-AT12  thank you.

**Comment by luan123z** [comment]
@KO-KMS-AT12 

Bạn có thể giải thích thêm những chỗ này giúp mình?
https://prnt.sc/vlfg15
