### ISSUE TITLE
Compatible with newer version of scikit-learn

### ISSUE THREAD

**Issue by trinhanhtuan** [undertheseanlp/underthesea#313]
Phiên bản UnderTheSea hiện tại (1.2.0a1) chỉ hoạt động được với Scikit-learn phiên bản 0.20.3 (khá cũ), phiên bản mới nhất là 0.23.2.

**Comment by rain1024** [comment]
Giống với #308

**Comment by mrdat0194** [comment]
giống với #308

**Comment by rain1024** [comment]
@trinhanhtuan Mình vừa cập nhật lại underthesea (phiên bản 1.2.1a0), hiện tại đã tương thích với scikit-learn <0.22.

Hiện tại scikit-learn >= 0.22 có một số API thay đổi với các mô hình của underthesea nên mình sẽ cần phải huấn luyện lại mô hình và cập nhật trong các phiên bản sau.

Thanks

**Comment by trinhanhtuan** [comment]
Tuyệt vời !!!

**Comment by rain1024** [comment]
@BLKSerene

> There is a problem when installing sklearn 0.21.3 (MP support), I have to manually install sklearn 0.20, so I truly hope that the the pin on sklearn version could be lifted.

I'm try to lift version of sklearn, but in the latest version (0.24.0), scikit-learn has an error in MacOS (see https://github.com/scikit-learn/scikit-learn/issues/19063)

Which version of sklearn you prefer?

**Comment by BLKSerene** [comment]
`0.23.2` would be better, or maybe wo would be better for `sklearn` to solve the problem on macOS.

**Comment by rain1024** [comment]
@BLKSerene 

> 0.23.2 would be better

Yeah, I'm retrained our classification models. The good news is these models will works well in sklearn>=0.23

> sklearn to solve the problem on macOS

I think they will fix it soon, perhaps in 0.24.1 as ogrisel mentioned

**Comment by rain1024** [comment]
@BLKSerene 

I've retrained classification and sentiment models with latest version of scikit-learn and release new version `1.3.1a2`.

Please check and let me know if there is any issue

Thanks,

**Comment by BLKSerene** [comment]
Thanks. It works. And, by the way, what about version pin of `torch` and `transformers`?

**Comment by rain1024** [comment]
@BLKSerene

> Thanks. It works.
Glad to hear that! 

> What about version pin of `torch` and `transformers`? 
Yeah, it because there are some errors with latest version of pytorch. However, I'm planning to remove it in the next releases.

**Comment by rain1024** [comment]
@trinhanhtuan Mình vừa cập nhật underthesea (phiên bản 1.3.1a2), tương thích với phiên bản scikit-learn mới nhất.

Bạn kiểm tra nhé ;)
