### ISSUE TITLE
Cách fix Error: Failed building wheel for scikit-learn  trên ubuntu linux

### ISSUE THREAD

**Issue by hotienky** [undertheseanlp/underthesea#343]
cho em hỏi sao em cài Underthrsea trên ubuntu thì nó bị lỗi Error: Failed building wheel for scikit-learn , em nghĩ là do mình chưa cài đặt visual studio c++ trên ubuntu , nên em hỏi cách khắc phục, nếu vấn đề là thiếu visual studio c++ thì em cài như thế nào được ạ, vì e nghĩ linux không hộ trợ visual studio 20xx

**Comment by rain1024** [comment]
@hotienky 

Em cài đặt `underthesea` như thế nào? 

Trên ubuntu, em chỉ cần gõ lệnh là được 

```
pip install underthesea
```

Em có thể xem thêm hướng dẫn ở video này https://youtu.be/hzVHepxkRL8?t=35

**Comment by hotienky** [comment]
@rain1024 
hiện tại em đang sử dụng python 3.8.5
khi em cài đặt python trên ubuntu linux e có ghé xem tài liệu này và làm theo https://codecute.com/python/huong-dan-cai-dat-lap-trinh-python-tren-ubuntu-linux.html
vì là python 3.8.5 nên em xài "pip3 install underthesea" để cài thư viện underthesea thì nó hiện tổng thể lỗi như sau 
![image](https://user-images.githubusercontent.com/50701813/98698678-e649b480-23a8-11eb-8774-7bd1f8bed6d6.png)
![image](https://user-images.githubusercontent.com/50701813/98698759-fe213880-23a8-11eb-8355-bf3611d61ae9.png)

**Comment by rain1024** [comment]
@hotienky Hiện tại, underthesea mới hỗ trợ **python 3.6**, chưa hỗ trợ **python 3.8** em nhé. 

Để sử dụng **python 3.6**, em thử dùng [venv](https://docs.python.org/3.6/library/venv.html) hoặc [anaconda](https://www.anaconda.com/) nhé

**Comment by rain1024** [comment]
@hotienky Anh vừa update version của underthesea lên `1.3.1a2`, tương thích với scikit-learn phiên bản mới hơn.

Em thử kiểm tra xem còn lỗi này không nhé.

Thanks ;)

**Comment by hotienky** [comment]
yes yes yes, thanks a nhé 👍

**Comment by duongkstn** [comment]
@rain1024 . Bạn ơi version `1.3.1.a2` không bị lỗi version `scikit-learn` nữa nhưng version `transformers` bạn để cao quá. Không biết bạn có thể hạ xuống version >=3.1.0, <= 3.5.1 không ạ ?

**Comment by rain1024** [comment]
@duongkstn Mình chưa đi sâu vào test các phiên bản khác nhau của transformers, mình sẽ thử và xem xét lại dependency nhé.

**Comment by TrisKnightGamer** [comment]
> @rain1024 . Bạn ơi version `1.3.1.a2` không bị lỗi version `scikit-learn` nữa nhưng version `transformers` bạn để cao quá. Không biết bạn có thể hạ xuống version >=3.1.0, <= 3.5.1 không ạ ?

@duongkstn này là lỗi version của torch! mong là fix sớm, chứ không xài được bữa giờ

**Comment by VuongNguyen2393** [comment]
Vẫn không cài được các bác ợ

**Comment by rain1024** [comment]
@VuongNguyen2393 

Em cho anh thông tin về môi trường của em, các câu lệnh em sử dụng cài đặt và lỗi nhé

**Comment by TrisKnightGamer** [comment]
> Vẫn không cài được các bác ợ

@VuongNguyen2393 lỗi từ các package phụ như là torch và transformer, không biết team đã fix chưa

**Comment by TrisKnightGamer** [comment]
> Vẫn không cài được các bác ợ

@VuongNguyen2393 lỗi từ các package phụ như là torch và transformer, không biết team đã fix chưa

**Comment by VuongNguyen2393** [comment]
> Bạn cho mình thông tin về môi trường của bạn, các câu lệnh bạn sử dụng để cài đặt và lỗi nhé

@rain1024 em cài trên window a ạ. 
Sử dụng **pip install underthesea** với python 3.9.5 thì báo lỗi như bạn @hotienky 
Chuyển qua **pip install underthesea==1.3.1a2** thì báo lỗi về torch cụ thể như sau ạ:
![image](https://user-images.githubusercontent.com/69831006/126858231-1152773e-016c-4214-a079-53f566861249.png)

**Comment by rain1024** [comment]
@VuongNguyen2393 em có thể chuyển sang python 3.6 không?

**Comment by VuongNguyen2393** [comment]
> @VuongNguyen2393 em có thể chuyển sang python 3.6 không?

@rain1024 e có thử sang python 3.6.5 những tình trạng vẫn thế a ạ. 

![image](https://user-images.githubusercontent.com/69831006/126862271-cbfa655b-beca-4593-a0ba-f927d94a2e1f.png)

**Comment by rain1024** [comment]
@VuongNguyen2393 Hiện tại underthesea không hỗ trợ Windows em nhé. Em thử trên Ubuntu/Centos hay dùng Ubuntu/CentOS trên Windows qua máy ảo hoặc docker em nhé

**Comment by TrisKnightGamer** [comment]
> @VuongNguyen2393 Hiện tại underthesea không hỗ trợ Windows em nhé. Em thử trên Ubuntu/Centos hay dùng Ubuntu/CentOS trên Windows qua máy ảo hoặc docker em nhé

@rain1024 lúc trước em cài ở Window dùng bình thường, sau này torch nó cập nhật, cài lại ở máy khác thì không dùng được.
