### ISSUE TITLE
Về gán nhãn trong POS Tagging, Chunking, NER và ý nghĩa

### ISSUE THREAD

**Issue by winchinh** [undertheseanlp/underthesea#349]
Em chào anh chị,

Em thấy Underthesea hỗ trợ tách từ và gán thẻ rất hay. Nhưng kiến thức hạn hẹp chưa hiểu hết ý nghĩa.
Ví dụ: Em truy cập vào http://undertheseanlp.com/#!/ và thử sử dụng một số câu để tìm hiểu thì
trong tính năng POS Tagging em biết một số thẻ: N-danh từ, V-động từ, A-tính từ, M-số từ, E-giới từ, R-trạng từ, Np-danh từ riêng
nhưng sang các thẻ của Chunking, NER thì em không hiểu lắm như B-NP, B-AP, B-VP, O, B-LOC, B-PER, I-PER,...
 
Anh, chị giúp em hiểu ý nghĩa các nhãn được dùng trong POS Tagging, Chunking, NER với ạ

Em chân thành cám ơn.

**Comment by rain1024** [comment]
Trùng với #312

**Comment by winchinh** [comment]
> Trùng với #312

Dạ, cám ơn anh

Anh có thể giải thích thêm giúp em một số từ viết tắt khi phân loại trong Chunking và NER với ạ

**Comment by rain1024** [comment]
Về nhãn Chunking, em tham khảo ở đây

https://github.com/undertheseanlp/underthesea/wiki/M%C3%B4-t%E1%BA%A3-d%E1%BB%AF-li%E1%BB%87u-b%C3%A0i-to%C3%A1n-Chunking

Về nhãn NER, em tham khảo ở đây 

https://vlsp.org.vn/vlsp2016/eval/ner

```
NE labels are annotated using the IOB notation as in the CoNLL Shared Tasks. There are 7 labels: B-PER and I-PER are used for persons, B-ORG and I-ORG are used for organizations, B-LOC and I-LOC are used for locations, and O is used for other elements.
```

**Comment by winchinh** [comment]
> @winchinh Về nhãn Chunking, em tham khảo ở đây
> 
> https://github.com/undertheseanlp/underthesea/wiki/M%C3%B4-t%E1%BA%A3-d%E1%BB%AF-li%E1%BB%87u-b%C3%A0i-to%C3%A1n-Chunking
> 
> Về nhãn NER, em tham khảo ở đây
> 
> https://vlsp.org.vn/vlsp2016/eval/ner
> 
> ```
> NE labels are annotated using the IOB notation as in the CoNLL Shared Tasks.
> 
> There are 7 labels:
> 
> - B-PER and I-PER are used for persons,
> - B-ORG and I-ORG are used for organizations,
> - B-LOC and I-LOC are used for locations,
> and O is used for other elements.
> ```

Dạ, @rain1024  anh thật tuyệt vời
Cám ơn anh rất nhiều ạ
Chúc anh thành công
