### ISSUE TITLE
🌊 Underthesea meet Deep Learning!

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#359]
From `underthesea v1.3.0`, we happy to pronounce `underthesea` will have **deep learning models**.

From 2017, underthesea stills is a small and light Vietnamese NLP library, we try to keep underthesea *easy to install and usage*. However,  at the moment (2020), we think **deep learning** are *too wonderful to ignore*, so we decide put our efforts to bring deep learning models in Vietnamese NLP via `underthesea`. 

💫 **It's a big update for us. Please give us your feedback and ideas here.**

### Progress

* **Update** Create a Vietnamese dependency parser using methods from [supar](https://github.com/yzhangcs/parser) package and [VLSP2020 Depedence Parsing Dataset](https://vlsp.org.vn/vlsp2020/eval/udp) (GH-157)

**Comment by thangnguyen69vt** [comment]
quá đã pepsi ơi
