### ISSUE TITLE
languageflow still exists in underthesea

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#364]
`languageflow` still exists in `underthesea\reader\tagged_corpus.py` and `underthesea\reader\tc_.py`, which causes `PyInstaller` to ask for the inclusion of `languageflow` when packaging my program (but `install_requires` in `setup.py` does not list it).
And it would be a lot help if underthesea could get rid of small dependencies like `unidecode` and `tabulate`.

**Comment by rain1024** [comment]
> `languageflow` still exists in `underthesea\reader\tagged_corpus.py` and `underthesea\reader\tc_.py`, which causes `PyInstaller` to ask for the inclusion of `languageflow` when packaging my program (but `install_requires` in `setup.py` does not list it).

Thanks for your comment. I will fix in v1.3.0 release

> And it would be a lot help if underthesea could get rid of small dependencies like `unidecode` and `tabulate`.
unidecode is very important to remove tone, so i think it's hard to get rid of it. `tabulate` is another story, I'm only use it to display table better. I will think about get rid of it.

**Comment by rain1024** [comment]
@BLKSerene **Version 1.3.0a2 is out**. `langaugeflow` and `tabulate` depencies have been removed. Please check it out.

**Comment by BLKSerene** [comment]
Thanks!

**Comment by BLKSerene** [comment]
There is a problem when installing sklearn 0.21 (MP support), I have to manually install sklearn 0.20, so I truly hope that the the pin on sklearn version could be lifted.

**Comment by rain1024** [comment]
Duplicate #313 

@BLKSerene I will retrained classification and sentiment model with sklearn soon. Please wait for a while
