### ISSUE TITLE
Vấn đề về định dạng font chữ

### ISSUE THREAD

**Issue by luan123z** [undertheseanlp/underthesea#382]
Chào bạn, mình đang sử dụng underthesea cho bài toán NER.

Kết quả trả về khá chính xác, tuy nhiên định dạng font chữ không trùng khớp với nhau, hãy xem ví dụ ở dưới đây

```
question = 'Đảo Phú Quốc có gì?'
named_entities = ner(question)
print(named_entities)
```

Output sẽ là:
```
[('Đảo', 'N', 'B-NP', 'B-LOC'), ('Phú Quốc', 'Np', 'I-NP', 'I-LOC'), ('có', 'V', 'B-VP', 'O'), ('gì', 'P', 'B-NP', 'O'), ('?', 'CH', 'O', 'O')]
```

Mình lấy text "Phú Quốc" từ biến question ở trên, và text "Phú Quốc" từ output của Under The Sea thì thấy 2 text này hoàn toàn khác nhau khi so sánh string bằng Python
Khi mình so sánh 2 text Phú Quốc thì lại không trùng khớp (có lẽ chắc không đúng định dạng): https://prnt.sc/wczffp

**Comment by rain1024** [comment]
@luan123z Vấn đề này là vấn đề encode
- Ở input, text chưa được chuẩn hóa
- Ở output, text đã được underthesea chuẩn hóa Unicode NFC

https://github.com/undertheseanlp/underthesea/blob/master/underthesea/feature_engineering/text.py#L4-L13

Về chuẩn hóa unicode https://unicode.org/faq/normalization.html
