### ISSUE TITLE
Corpus for training Named Entity Recognition model

### ISSUE THREAD

**Issue by huyphat98** [undertheseanlp/underthesea#391]
Cho em hỏi corpus dataset ban đầu dùng để train cho model này nhóm lấy ở đâu? có thể chia sẻ không?

**Comment by rain1024** [comment]
@huyphat98 Em hỏi model nào nhỉ?

**Comment by huyphat98** [comment]
dạ cái model NER đó anh. Anh có thể chia sẽ cái dataset anh dùng để train được không ạ

**Comment by rain1024** [comment]
@huyphat98 Hiện tại mô hình của underthesea được train trên dữ liệu VLSP2016 NER và VLSP2018 NER em nhé.

underthesea không sở hữu và không có quyền phân phối dữ liệu VLSP. Em hãy email vào địa chỉ vlsp.resources@gmail.com để xin trực tiếp nhóm tác giả em nhé

Thanks
