### ISSUE TITLE
Có thể dùng underthesea để tách từ tiếng việt không dấu không?

### ISSUE THREAD

**Issue by linh1995** [undertheseanlp/underthesea#398]
Mình đang có bài toán về tách từ tiếng việt không dấu
Đầu vào mình là: Khanh linh la mot co gai tot
-> đầu ra mình muốn: khanh linh , la, mot, co gai, tot

**Comment by rain1024** [comment]
Duplicate of #200

**Comment by rain1024** [comment]
Bạn tham khảo ở issue #200 nhé
