### ISSUE TITLE
Error while request torch with unavailable with torch<=1.5.1,>=1.1.0

### ISSUE THREAD

**Issue by TrisKnightGamer** [undertheseanlp/underthesea#400]
ERROR: Could not find a version that satisfies the requirement torch<=1.5.1,>=1.1.0 (from underthesea==1.3.1) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.7.0, 1.7.1, 1.8.0, 1.8.1)
ERROR: No matching distribution found for torch<=1.5.1,>=1.1.0 (from underthesea==1.3.1)

**Comment by rain1024** [comment]
Please provide your enviroment and your command to reproduce this error

**Comment by TrisKnightGamer** [comment]
i use python 3.7 and use pip install underthesea

**Comment by rain1024** [comment]
> i use python 3.7 and use pip install underthesea

Can you use python 3.6, underthesea is fully tested in python 3.6. Your error may caused by python 3.7 cannot find suitable torch version

Anyway, I will try to update torch version later.
