### ISSUE TITLE
cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler'

### ISSUE THREAD

**Issue by minhdang241** [undertheseanlp/underthesea#403]
I cannot import the underthesea module after installing using `pip install underthesea`. The error seems from the import of SAVE_STATE_WARNINING. I am using PyTorch version 1.8.

```
     38     SAVE_STATE_WARNING = ""
     39 else:
---> 40     from torch.optim.lr_scheduler import SAVE_STATE_WARNING
     41 
     42 logger = logging.get_logger(__name__)

ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)
```

It seems like the `SAVE_STATE_WARNING`  constant was removed from this merged https://github.com/pytorch/pytorch/pull/46813.

I am trying to install a newer version of transformers by myself and it helps. Please consider updating the requirements transformer for underthesea.

**Comment by rain1024** [comment]
@minhdang241 Thanks for your report. underthesea is only support for specific torch version torch>=1.1.0,<=1.5.1

I will support newer version of torch in next release

**Comment by rain1024** [comment]
@minhdang241 I'm going to work on this prolem. 

I will change dependencies to `torch>=1.0` (according to [`transformers`](https://github.com/huggingface/transformers/blob/master/setup.py) library)

**Comment by rain1024** [comment]
@minhdang241 Today I updated `torch` and `transformers` dependencies and release underthesea v1.3.3a0.

You can try to install this version and tell me whether the error still exist or not..

```
pip install underthesea==1.3.3a0
```

Feel free to reopen this issue if the error still exist. Thank you
