### ISSUE TITLE
Is there a plan to wrap this project in Java ?

### ISSUE THREAD

**Issue by tonyphong** [undertheseanlp/underthesea#406]
This is very useful project, but it only available in Python. So I'd like to write an Elasticsearch plugin (in Java) so that we can use this project in an Elasticsearch way

Is there a plan to wrap this project in Java api ?

**Comment by rain1024** [comment]
Hi @tonyphong, thanks for using underthesea.

At the moment, we don't have any plan about develop Java wrapper. We will consider about it in the future.

Thanks for your suggestion.
