### ISSUE TITLE
làm sao add resource  vào underthesea cài đặt trên window

### ISSUE THREAD

**Issue by hoaiphanuel** [undertheseanlp/underthesea#407]
xin hướng dẫn add resource cho một số bộ như VNTC,  TC_Bank....   để sử dụng trong  classify v.v  
mình cài đặt  trên windows nên không dùng cách  dowdload như hướng dẫn
cám ơn

**Comment by rain1024** [comment]
Hiện tại underthesea không hỗ trợ Windows bạn nhé. Bạn có thể chuyển sang Linux hay dùng Linux trên Windows qua máy ảo hoặc docker nhé
