### ISSUE TITLE
Có kế hoạch phát triển underthesea cho Windows không?

### ISSUE THREAD

**Issue by huytranaz** [undertheseanlp/underthesea#449]
Cho mình hỏi các bạn có kế hoạch phát triển underthesea cho Windows không và khi nào ạ?

**Comment by rain1024** [comment]
Same as #407 

Cảm ơn câu hỏi của @huytranaz nhé.

Hiện tại team cũng đang rất muốn hỗ trợ underthesea. Ý tưởng chính của team là sẽ sử dụng Github Actions để build wheel, sau đó publish lên pip và conda.

Tuy nhiên, trong thời điểm hiện tại, nguồn lực của team không có đủ resource để thực hiện công việc này. Trong khoảng 6 tháng tới, feature này vẫn pending @huytranaz nhé.

**Comment by rain1024** [comment]
@huytranaz 

Hiện tại, mình có vừa build một bản underthesea phiên bản v1.3.4a2 cho windows. Bạn test thử xem nhé

```
pip install underthesea==1.3.4a2
```

**Comment by huytranaz** [comment]
Cảm ơn bạn nhiều nhé, mình sẽ thử :)

Được gửi từ iPhone của tôi
