### ISSUE TITLE
Provide training script for word segmentation and pos tagging and named entity recognition

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#502]
In the next version (v1.3.4) of underthesea, we try to provide training script for word semgntation and pos tagging, chunking and named entity recognition

**Comment by rain1024** [comment]
@ngovanminh3232 Trong thời gian tới, mình sẽ cập nhật thông tin về việc đưa ra hướng dẫn huấn luyện word segmentation và pos tagging trong issue này.

Em theo dõi vào thảo luận ở đây nhé.

**Comment by rain1024** [comment]
Checklist 

**Word Segmentation**

- [ ] Provide standardized training workflow
- [ ] Create an open and accessible dataset (UTS_WTK_v1)

**Comment by rain1024** [comment]
@ngovanminh3232 👋 Anh vừa release underthesea version 6.1.3, anh có cung cấp open dataset và training pipeline cho bài toán tách từ trên Google Colab https://colab.research.google.com/drive/1NR9NlHJDj5_wywRze7yQizw1DgICKL72?usp=sharing

Em tham khảo nhé. Chúc em thành công 🕺

**Comment by ngovanminh3232** [comment]
Em cảm ơn anh @rain1024 , em sẽ thử lại sau ạ ❤️
