### ISSUE TITLE
Illegal hardware instruction

### ISSUE THREAD

**Issue by miracuong** [undertheseanlp/underthesea#503]
Hello team,

Mình đang có issue là khi mình import underthesea trong terminal thì bị lỗi "illegal hardware instruction python", mình thử import trong jupyter notebook thì bị dead kernel. Mình đang dùng macbook M1 và python version là 3.8.8, không biết lỗi này có phải là do underthesea chưa support trên M1 không nhỉ? 

Thanks team.

**Comment by rain1024** [comment]
@miracuong Hiện tại team chưa test underthesea trên M1 bạn nhé.

>  khi mình import underthesea trong terminal thì bị lỗi "illegal hardware instruction python"
Bạn cài đặt underthesea và lỗi chi tiết như thế nào nhỉ

**Comment by miracuong** [comment]
> @miracuong Hiện tại team chưa test underthesea trên M1 bạn nhé.
> 
> > khi mình import underthesea trong terminal thì bị lỗi "illegal hardware instruction python"
> 
> Bạn cài đặt underthesea và lỗi chi tiết như thế nào nhỉ

Mình có thử cài lại trên env khác thì chạy ổn rồi, mình nghĩ lí do là bị conflict với các thư viện khác. Cảm ơn team ạ.
