### ISSUE TITLE
Lite version for underthesea

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#505]
In production, in many cases, I think people just need a lite `word_tokenize` function, so I decide to make a lite version by default for underthesea.

It won't include deep learning dependencies (torch, transformers) and dependencies for training (pytorch-lightning, seqeval)

Solutions:

* I will use *extras_require* ([1](https://stackoverflow.com/a/45042691/772391), [2](https://hynek.me/articles/conditional-python-dependencies/)) and *lazy_loading module import* ([3](https://stackoverflow.com/questions/17546314/lazy-loading-module-imports-in-an-init-py-file-python), [4](https://www.python.org/dev/peps/pep-0562/)) in `setup.py`  to do this task

**Comment by namhoai167** [comment]
Hi @rain1024, that what exactly what I need. How can I use this lite version?
