### ISSUE TITLE
Word Segmentation error

### ISSUE THREAD

**Issue by nnt296** [undertheseanlp/underthesea#528]
Thanks for such a great NLP library. Yet, I run into this error when trying to segment the following sentence. Could you double-check it.

Input:
- Ubuntu 20.04
- Python 3.8
- UTS version 1.3.4

```
uts.word_tokenize("000 85 .")
```

Output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/miniconda3/envs/nlpp/lib/python3.8/site-packages/underthesea/pipeline/word_tokenize/__init__.py", line 42, in word_tokenize
    output[-1] = output[-1] + u" " + token
IndexError: list index out of range
```

**Comment by rain1024** [comment]
@nnt296 Thank you so much for reporting this issue.

I fixed it in underthesea version `1.3.5a0`. Please try it

Update underthesea 

```
pip install underthesea==1.3.5a0
```

Use `word_tokenize` function 

```
>>> from underthesea import word_tokenize
>>> text = "000 85 ."
>>> word_tokenize(text)
['000', '85', '.']
```
