### ISSUE TITLE
Runtime error: `GLIBC_2.18' not found 

### ISSUE THREAD

**Issue by melody-rain** [undertheseanlp/underthesea#530]
I got this error: 
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by python3.6/site-packages/underthesea_core.cpython-36m-x86_64-linux-gnu.so)

Any solutions? 
My OS is Centos 7  and GLIBC_2.17 is valid on my OS. Upgrading to GLIBC_2.18 is not valid.

**Comment by Gooklim** [comment]
Hi, I think can try to install python-crfsuite==0.9.6, it worked fine for me.

**Comment by melody-rain** [comment]
> Hi, I think you can try to install python-crfsuite==0.9.6, it worked fine for me.

@Gooklim  Hi. I've tried but I am afraid it does not work. The same error happens. And I don't think the problem has relation with python-crfsuite.

**Comment by Gooklim** [comment]
Hi, rain, I am sorry I was not clear that I am actually using python-crfsuite==0.9.6 with underthesea==1.2.0, without underthesea_core dependency.
And, the reason I told you to use that version of python-crfsuite is that I assumed the only thing related to GLIBC in the package is CRF module. maybe I was wrong. sorry for that.
Hope it will go well this time :)

**Comment by melody-rain** [comment]
thank you for your kind reply.

Sent from my iPhone

On Jun 23, 2022, at 15:51, Gooklim ***@***.***> wrote:

﻿

Hi, rain, I am sorry I was not clear that I am actually using python-crfsuite==0.9.6 with underthesea==1.2.0, without underthesea_core dependency.
And, the reason I told you to use that version of python-crfsuite is that I assumed the only thing related to GLIBC in the package is CRF module. maybe I was wrong. sorry for that.
Hope it will go well this time :)

**Comment by rain1024** [comment]
Today, I face a similar issue. I update version underthesea 1.3.5a2. It works very well in my system (Ubuntu 20.04, python 3.7). However, when I install run this library in [google colab](https://colab.research.google.com/drive/1gD8dSMSE_uNacW4qJ-NSnvRT85xo9ZY2#scrollTo=CsCOAn35ZI9r). 

```
$ pip install underthesea==1.3.5a2

$ python
>>> import underthesea

ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/lib/python3.7/dist-packages/underthesea_core.cpython-37m-x86_64-linux-gnu.so)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
-----------------------------------------
```

**Comment by rain1024** [comment]
@melody-rain @Gooklim I'm very happy to announce that underthesea version 1.3.5a3 is now suport glibc 2.17 (centos 7).

Please give it a try and let me know if It works.
