### ISSUE TITLE
Does underthesea support GPU accelerator ? 

### ISSUE THREAD

**Issue by hduc-le** [undertheseanlp/underthesea#531]
Hi guys, I'm working on a project using the underthesea library for dependency parsing tasks. Everything is okay when I work with CPU mode, however, if I activate GPU mode, I will receive an error message as below:

RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor.

So, I wonder does the underthesea support GPU mode?

**Comment by rain1024** [comment]
Please give me more information about your environments and your commands
