### ISSUE TITLE
không cài đặt được trên pycharm trên hệ điều hành macos monterey(macbook pro, m1,2020 )

### ISSUE THREAD

**Issue by ongbataolohet** [undertheseanlp/underthesea#532]
không cài đặt được trên pycharm trên hệ điều hành macos monterey(macbook pro, m1,2020 ) trong project có cài đặt môi trường miniforge để hỗ trợ cài đặt tensorflow

**Comment by rain1024** [comment]
@ongbataolohet Hi bạn,

Bạn đã chạy những lệnh nào, lỗi như thế nào bạn nhỉ?

**Comment by ongbataolohet** [comment]
@rain1024 mình $pip install underthesea trên Terminal trong pycharm thì nó hiện dòng chữ này "ERROR: Could not build wheels for tokenizers, which is required to install pyproject.toml-based projects" trong đó project của mình có cài đặt minifore3 để tạo môi trường có thể pip được tensorflow

**Comment by rain1024** [comment]
@ongbataolohet Bạn dùng python version nào? Bạn thử sử dụng [conda](https://docs.conda.io/en/latest/) xem có được không nhé

```
conda create -n lab_underthesea python=3.8
conda activate lab_underthesea
pip install underthesea
```

**Comment by ongbataolohet** [comment]
@rain1024  cảm ơn anh ạ

**Comment by rain1024** [comment]
Em dùng `conda` để tạo environment python 3.8 nhé
```
conda create -n lab_underthesea python=3.8
```
