### ISSUE TITLE
Cannot install pip install underthesea_core==0.0.4_alpha.10 trên Window 10, python 3.8

### ISSUE THREAD

**Issue by antuong12c2** [undertheseanlp/underthesea#533]
Hi team, I cannot upgrade underthesea to latest  version
Because i can not install  underthesea_core version 0.0.4_alpha.10
![image](https://user-images.githubusercontent.com/11646105/169197102-9f14b3ac-31a2-43ee-9f29-3feb06b46bcc.png)

Please help me check this, thank you

**Comment by antuong12c2** [comment]
Mình cài bản 1.3.0 thì bị lỗi này, 
ERROR: Could not find a version that satisfies the requirement torch<=1.5.1,>=1.1.0 (from underthesea) (from versions: none)
![image](https://user-images.githubusercontent.com/11646105/169197976-2db968f0-2164-4477-a77f-a880deba6ebd.png)

**Comment by rain1024** [comment]
@antuong12c2

1. Bạn sử dụng anaconda để tạo môi trường python nhé
2. Bạn hãy thử sử dụng phiên bản 1.3.4 xem 

```
conda create -n lab_underthesea python=3.8
conda activate lab_underthesea
pip install underthesea==1.3.4
```

**Comment by NguyenCongHaiNam** [comment]
> pip install underthesea==1.3.4

<img width="684" alt="image" src="https://github.com/undertheseanlp/underthesea/assets/116544941/603a2c80-4555-4944-93cf-80169c0c3c33">
Mình bị lỗi này thì làm thế nào ạ
