### ISSUE TITLE
Wrong tokens when tokenize long text

### ISSUE THREAD

**Issue by kitoshitachi** [undertheseanlp/underthesea#536]
![image](https://user-images.githubusercontent.com/92215956/175940608-38d89105-501e-4ac2-b4d5-327ba7b83506.png)
![image](https://user-images.githubusercontent.com/92215956/175940773-51170442-b8c7-4e35-aba8-5fc5491c25e2.png)
t đã thử 1 vài đoạn test với dấu chấm. ví dụ như
"something . Bạn đang làm gì" và tôi sẽ nhận được 1 token là ". Bạn"
điều tôi mong muốn là "." và "Bạn"

**Comment by rain1024** [comment]
@kitoshitachi Cảm ơn report của bạn

Mình đã thử với underthesea version 1.3.4, nếu sử dụng `word_tokenize` trực tiếp đối với những text có nhiều câu, sẽ bị lỗi dính token `.` vào từ kế tiếp

```
>>> from underthesea import word_tokenize
>>> text = 'Bạn chỉ làm điều này với chính bản thân mình . Bạn tự làm chủ'
>>> word_tokenize(text)
['Bạn',
 'chỉ',
 'làm',
 'điều',
 'này',
 'với',
 'chính',
 'bản thân',
 'mình',
 '. Bạn',      <-- wrong
 'tự',
 'làm chủ']
```

Để fix lỗi này, bạn có thể sử dụng hàm tách câu `sent_tokenize` trước , sau đó sử dụng hàm tách từ `word_tokenize`

```
>>> from underthesea import sent_tokenize
>>> from underthesea import word_tokenize
>>> text = 'Bạn chỉ làm điều này với chính bản thân mình . Bạn tự làm chủ'
>>> sentences = sent_tokenize(text)
>>> for s in sentences:
>>>     print(word_tokenize(s))
['Bạn', 'chỉ', 'làm', 'điều', 'này', 'với', 'chính', 'bản thân', 'mình', '.']
['Bạn', 'tự', 'làm chủ']
```
