### ISSUE TITLE
Run lỗi

### ISSUE THREAD

**Issue by chuyendq9x** [undertheseanlp/underthesea#539]
![image](https://user-images.githubusercontent.com/21030546/172420370-9da6e37a-7a3d-4375-bdfc-50dddbe63828.png)
![image](https://user-images.githubusercontent.com/21030546/172420448-44e82025-8f3d-457b-ae27-7a2448b7785a.png)

Tôi chạy project thì báo lỗi này. Tôi có tìm ở util  và không thấy file crf. Thêm nữa tôi muốn train thêm data của mình. cho tôi xin mẫu dataset

**Comment by rain1024** [comment]
Same as #502
