### ISSUE TITLE
Dependency Parsing HTTPError

### ISSUE THREAD

**Issue by pdhlong** [undertheseanlp/underthesea#540]
Hi, tried to use underthesea's dependency parsing on colab but got this error. Can you have a look. Thank you.
![image](https://user-images.githubusercontent.com/59214698/183061752-d8696bdc-5c0d-456d-808a-8bc610eb0390.png)

**Comment by rain1024** [comment]
Hi @pdhlong 

There are some errors related with resources path. I've fixed it and update underthesea version 1.3.5a1.
I also update colab document https://colab.research.google.com/drive/1gD8dSMSE_uNacW4qJ-NSnvRT85xo9ZY2

Please test it and let me know if it works. Thank you so much for reporting this bug.

**Comment by pdhlong** [comment]
It works now! Thank you for your help.

**Comment by pdhlong** [comment]
Hi, may I ask what the UAS of the current dependency parser is? Thank you.

**Comment by rain1024** [comment]
@pdhlong UAS is 81.53% on VLSP 2020 test set.

Please read more detail in this technical report https://github.com/undertheseanlp/underthesea/blob/master/examples/dependency_parsing/docs/vlsp2020_technical_report/vlsp2020_dp_technical_report_20201217.pdf
