### ISSUE TITLE
bug not use text_normalize

### ISSUE THREAD

**Issue by Dean98AI** [undertheseanlp/underthesea#557]
I can not use text_normalize in version 1.3.4 , when use text_normalize ?
Thanks guys

**Comment by rain1024** [comment]
@Dean98AI By using `text_normalize`, you must install version `1.3.5a3`

```
$ pip install underthesea==1.3.5a3
```

then use `text_normalize`

```
from underthesea import text_normalize
text_normalize('Ðảm baỏ chất lựơng phòng thí nghịêm hoá học')
# Đảm bảo chất lượng phòng thí nghiệm hóa học
```

`text_normalize` is still in alpha version. We will release `text_normalize` in stable version (1.3.5) soon.

Please try it and feel free to let us know what you think.

**Comment by Dean98AI** [comment]
Thank u so much !

**Comment by Dean98AI** [comment]
I haved used to improve sentence in customer serivce but no improve about type error, spell error,... and only split number and character , i wish improve this error above in next version
`à ok m đặt bàn 7 8ng thôi -> à ok m đặt bàn 7 8 ng thôi`
`ok bạn cố giúp m k quá 48h -> ok bạn cố giúp m k quá 48 h`

**Comment by rain1024** [comment]
what is your expectation input for text `à ok m đặt bàn 7 8ng thôi` ?

**Comment by Dean98AI** [comment]
i want to become à oke m đặt bàn 7 8 người thôi / à oke mình đặt bàn 7 8 người thôi 
ex 2 -> oke bạn cố giúp m không quá 48h/ oke bạn cố giúp mình không quá 48h 

-> i mean that model don't handle about spell correct and type error ,... but only split number with character

**Comment by rain1024** [comment]
`à oke m đặt bàn 7 8 người thôi`  ->  `à oke mình đặt bàn 7 8 người thôi`
-> now I already see your point.

`i mean that model don't handle about spell correct and type error ,... but only split number with character`

-> You're correct, it still hasn't dealt with spell correction yet. I think it will be future feature.

**Comment by Dean98AI** [comment]
Thanks guys :100:
