### ISSUE TITLE
issues import text_normalize

### ISSUE THREAD

**Issue by FamCao** [undertheseanlp/underthesea#562]
ImportError                               Traceback (most recent call last)
[<ipython-input-15-4d5c2bcc2055>](https://localhost:8080/#) in <module>
----> 1 from underthesea import text_normalize

ImportError: cannot import name 'text_normalize' from 'underthesea' (/usr/local/lib/python3.7/dist-packages/underthesea/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by rain1024** [comment]
Duplicate #557

**Comment by rain1024** [comment]
@FamCao `text_normalize` is out on version 1.3.5

Please check it out

```
pip install underthesea
```

Use `text_normalize` module

```
>>> from underthesea import text_normalize
>>> text_normalize('Ðảm baỏ chất lựơng phòng thí nghịêm hoá học')
'Đảm bảo chất lượng phòng thí nghiệm hóa học'
```
