### ISSUE TITLE
Add CI for underthesea sentiment example

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#563]
Currently, `examples` is where we put our experiments about training models. We `ner`, `sentiment`, `text_normalize`, `chatbot`. I think it would be better if we have Github actions for this code.

**Comment by rain1024** [comment]
@hungpham3112 As I mentioned in PR #561, I add PR  #564 for CI in sentiment example. In this CI, I run sentiment example in various operating system (ubuntu-latest, windows-latest, mac-latest)

Please check [these PR][https://github.com/undertheseanlp/underthesea/pull/564] and [github action file](https://github.com/undertheseanlp/underthesea/blob/master/.github/workflows/ci-examples.yml) if you're interested in sentiment example. 

Thanks,

**Comment by hungpham3112** [comment]
Can you update the new version of underthesea in PyPI? `pip install underthesea` is still using the old version. Thanks

**Comment by rain1024** [comment]
@hungpham3112 If you want to install latest version of underthesea, please add specific version in `pip install`

```
pip install underthesea==1.3.5a3
```

`1.3.5a3` is pre-release version. Stable version `1.3.5` wil be updated soon.
