### ISSUE TITLE
Text Classification - how to update additional domain 

### ISSUE THREAD

**Issue by thangvc91** [undertheseanlp/underthesea#567]
Dear team, 
This project really useful for me, however that would be great if you can assist how to update additional library for Text Classification function.

**Comment by rain1024** [comment]
@thangvc91 Very nice idea. 

Which domain you want to add to text_classifcation function?

**Comment by thangvc91** [comment]
Hi @rain1024 ,
Thank you so much, I would like to add some fields related insurance. I'm new in ML so i got  a bit difficulty to understand your code for  text classification , but nevermind I'll try to figure out this :)
