### ISSUE TITLE
Improve tokenizer

### ISSUE THREAD

**Issue by rain1024** [undertheseanlp/underthesea#568]
Ideas for tokenizer improvement

**Comment by tiendung** [comment]
1/ Với TV có lẽ cần bước tiền xử lý các âm tiết trước khi cho vào bộ wordpiece (của BERT). vì nhiều khi mình có nhiều cách bỏ dấu khác nhau và mã hóa (unicode) khác nhau. Nên chuẩn hoá về 1 dạng trước

2/ Giả sử tập huấn luyện chỉ toàn âm tiết tiếng Việt thì mình tìm hiểu các cách bẻ âm tiết thanh các đơn vị nhỏ hơn anh nghĩ là bài toán thú vị, vì lúc đó wordpiece (BPE based) sẽ ko còn nhiều giá trị.

ví dụ nhé: nếu áp dụng BPE thì "á, à, ả, ã, ạ” là 3 symbols khác nhau hoàn toàn nhưng với tiếng Việt chúng là nguyên âm `a` kết hợp với `thanh điệu sắc` (sharp tone).  Và trong trường hợp viết ko dấu, gõ nhầm dấu thì việc giữ lại thể hiện `nguyên âm + thanh điệu` sẽ giúp máy tận dụng nguyên âm và sửa sai tốt hơn.

Kiểu như: Hà LÁn, mà BPE bước 1 thì thành `H à L á n`, còn bẻ theo ngữ âm thành: `ha|f lan|s` chẳng hạn.

**Comment by rain1024** [comment]
@tiendung 

> `Với TV có lẽ cần bước tiền xử lý các âm tiết trước khi cho vào bộ wordpiece (của BERT). vì nhiều khi mình có nhiều cách bỏ dấu khác nhau và mã hóa (unicode) khác nhau. Nên chuẩn hoá về 1 dạng trước` 

Cái này em cũng đang làm một bộ chuẩn hoá, anh xem thử xem okie không nhé

```
pip install underthesea==1.3.5a3
```

Run `text_normalize`

```
>>> from underthesea import text_normalize
>>> text_normalize('Ðảm baỏ chất lựơng phòng thí nghịêm hoá học')
'Đảm bảo chất lượng phòng thí nghiệm hóa học'
```

> `Giả sử tập huấn luyện chỉ toàn âm tiết tiếng Việt thì mình tìm hiểu các cách bẻ âm tiết thanh các đơn vị nhỏ hơn anh nghĩ là bài toán thú vị, vì lúc đó wordpiece (BPE based) sẽ ko còn nhiều giá trị.`

Cái này có gì benchmark được không anh nhỉ?

**Comment by tiendung** [comment]
> ```
> >>> from underthesea import text_normalize
> >>> text_normalize('Ðảm baỏ chất lựơng phòng thí nghịêm hoá học')
> 'Đảm bảo chất lượng phòng thí nghiệm hóa học'
> ```

Cool :)

> > `Giả sử tập huấn luyện chỉ toàn âm tiết tiếng Việt thì mình tìm hiểu các cách bẻ âm tiết thanh các đơn vị nhỏ hơn anh nghĩ là bài toán thú vị, vì lúc đó wordpiece (BPE based) sẽ ko còn nhiều giá trị.`
> 
> Cái này có gì benchmark được không anh nhỉ?

Được chứ bằng cách so sánh perf của BERT trên nhiều cách tknz khác nhau.

Tiếng Trung họ đã có thử nghiệm rồi [Sub-Character Tokenization for Chinese Pretrained Language Models](https://arxiv.org/pdf/2106.00400.pdf)

<img width="611" alt="Screen Shot 2022-09-11 at 10 58 20" src="https://user-images.githubusercontent.com/8133/189511792-8e732007-04cc-4ae5-8cbd-78d374e87528.png">

Họ có thử nghiệm `Char-based encoding` (tương đương với syllable-based trong tiếng Việt) vs `Pronunciation-based encoding` (chữ tượng thanh) vs ` Glyph-based encoding` (nét chữ tượng hình).

**Comment by rain1024** [comment]
> Họ có thử nghiệm Char-based encoding (tương đương với syllable-based trong tiếng Việt) vs Pronunciation-based encoding (chữ tượng thanh) vs Glyph-based encoding (nét chữ tượng hình).

Kết quả thế nào anh nhỉ?

**Comment by tiendung** [comment]
> Kết quả thế nào anh nhỉ?
more efficient and more robust.

more efficient: giảm số lượng tokens trong 1 câu, giúp tăng tốc huấn luyện ...
more robust: chịu được typo tốt hơn ...

Em nên đọc hết paper để nắm được hết các khía cạnh thú vị. Ví dụ nhé:

<img width="611" src="https://user-images.githubusercontent.com/8133/189511792-8e732007-04cc-4ae5-8cbd-78d374e87528.png">

1/ SubChar-Pinyin là biểu diễn dưới dạng phát âm, cho kq tốt nhất. 

2/ Họ dùng sentence-piece để phân tách tokens nên các token vượt qua ranh giới từ (điểm khác biệt lớn với wordpiece). Trong hình trên phân tách kiểu sub-word có 12 tokens. Còn phân tách sub-char thì giảm còn 7 tokens.

3/ Trong SubChar-Pinyin, các con số khoanh tròn (1), (2), (3), (4) chính là thanh điệu. Họ để ở cuối âm tiết.

**Comment by rain1024** [comment]
This issue was closed because it has been inactive for 7 days since being marked as stale.

 Please feel free to reopen it if you need any further support.
