### ISSUE TITLE
Remove unidecode as a dependency

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#569]
As raised up and discussed in #364, `unidecode` is used for removal of diacritics in Vietnamese. But since there are only 6 vowel letters 
 (Ă/ă, Â/â, Ê/ê, Ô/ô, Ơ/ơ, Ư/ư) and 1 consonant letter (Đ, đ) that have diacritics, and 6 vowel letters with diacritics and 5 tone marks conbined (30 characters in total), I suppose that a simple conversion table would suffice for the diacritic removal task?

Currently `unidecode` is used in [pipeline.classification.text_features](https://github.com/undertheseanlp/underthesea/blob/c9093183553a4b6efbf4118f792bfabfbefa49ff/underthesea/pipeline/classification/text_features.py#L27), [pipeline.sentiment.bank.text_features](https://github.com/undertheseanlp/underthesea/blob/c9093183553a4b6efbf4118f792bfabfbefa49ff/underthesea/pipeline/sentiment/bank/text_features.py#L27), and [pipeline.sentiment.general.text_features](https://github.com/undertheseanlp/underthesea/blob/c9093183553a4b6efbf4118f792bfabfbefa49ff/underthesea/pipeline/sentiment/general/text_features.py#L27). It would be better to have a single definition of the function `remove_tone` and then being referenced elsewhere, but I'm not sure where the definition should go. (The 3 files are largely the same, maybe merge them into 1 file?) I could work on this and would send a PR.

I do not speak Vietnamese though, so I'm not sure about this. Am I missing anything else?

**Comment by rain1024** [comment]
@BLKSerene Good idea. I'm doing the text_normalize module, so I think now we can implement `remove_tone` easily as your suggestion.

**Comment by rain1024** [comment]
@BLKSerene Thanks for your contribution. I release underthesea version `1.4.0-alpha` for this PR. Please check it out 

```
pip install underthesea==1.4.0a0
```
