### ISSUE TITLE
Hỗ trợ từ viết tắt

### ISSUE THREAD

**Issue by lehoangHUST** [undertheseanlp/underthesea#570]
E chào a  ạ, cho em hỏi chút là code đã hỗ trợ cho phần từ viết tắt chưa ạ (giả sử tphcm : thành phố hồ chí minh).

**Comment by rain1024** [comment]
@lehoangHUST chưa em nhé. 

Nhưng anh có thể xử lý đơn giản bằng cách mapping được. 

Anh cũng đang dự định extend function `text_normalize` 

```
text_normalize('tphcm') -> tphcm
text_normalize('tphcm', t=0.9) -> thành phố Hồ Chí Minh
```

**Comment by lehoangHUST** [comment]
em nghĩ mapping được nhưng mà số lượng từ viết tắt nó khá là nhiều 
e nghĩ nên mở rộng extend function cho từ viết tắt a ạ

**Comment by rain1024** [comment]
Em có list từ viết tắt không?

**Comment by lehoangHUST** [comment]
Hiện e tìm được trang github này cx khá nhiều a ạ
https://github.com/v-nhandt21/Vinorm/tree/master/build/lib/vinorm/Mapping
A xem thử ạ
