### ISSUE TITLE
Move scikit-learn to extras_require

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#586]
Similar to #505, I only use `sent_tokenize`, `word_tokenize`, `pos_tag`, and `sentiment` for Vietnamese NLP tasks in my project. I have tested that these functinos do not depend on `scikit-learn`, which is a large dependency.

So I'm wondering that whether it is possible to also move `scikit-learn` to `extras_require` as done in #506 so that lite users of `underthesea` do not have to install such a large 3rd-party library?

**Comment by rain1024** [comment]
Actualy, `sentiment` is using `scikit-learn`

https://github.com/undertheseanlp/underthesea/blob/c92bca3c00e85797bf09a6d5aeaab418927a7aea/underthesea/models/text_classifier.py#L61

when `joblib.load` load model, it a [`LinearSVC`](https://scikit-learn.org/stable/modules/generated/sklearn.svm.LinearSVC.html#sklearn.svm.LinearSVC) object
