### ISSUE TITLE
Please upload dependence parsing module

### ISSUE THREAD

**Issue by htluandc2** [undertheseanlp/underthesea#597]
Hi there, when i run:

from underthesea import dependency_parse
text = 'Tối 29/11, Việt Nam thêm 2 ca mắc Covid-19'
dependency_parse(text)

Then dependence file can not download.
Downloading: "https://github.com/undertheseanlp/underthesea/releases/download/v1.3-resources/vi-dp-v1a1.zip" to vi-dp-v1a1.zip

File /opt/homebrew/Caskroom/miniforge/base/envs/env_tf/lib/python3.9/urllib/request.py:641, in HTTPDefaultErrorHandler.http_error_default(self, req, fp, code, msg, hdrs)
    640 def http_error_default(self, req, fp, code, msg, hdrs):
--> 641     raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: HTTP Error 404: Not Found

Please upload this file. 
Thank you very much!

**Comment by rain1024** [comment]
@htluandc2 Which version of underthesea are you using?

```
$ underthesea info 
```

or use pip

```
$ pip freeze | grep underthesea
```

This error is fixed in underthesea version 1.3.5. You should update underthesea version

```
$ pip install underthesea[deep]==1.3.5


>>> from underthesea import dependency_parse
>>> text = 'Tối 29/11, Việt Nam thêm 2 ca mắc Covid-19'
>>> dependency_parse(text)
>>> from underthesea import dependency_parse
>>> text = 'Tối 29/11, Việt Nam thêm 2 ca mắc Covid-19'
>>> dependency_parse(text)
[('Tối', 5, 'obl:tmod'),
 ('29/11', 1, 'flat:date'),
 (',', 1, 'punct'),
 ('Việt Nam', 5, 'nsubj'),
 ('thêm', 0, 'root'),
 ('2', 7, 'nummod'),
 ('ca', 5, 'obj'),
 ('mắc', 7, 'nmod'),
 ('Covid-19', 8, 'nummod')]
```

**Comment by htluandc2** [comment]
Thank you for your immediate support. 
But when I reinstall underthesea, I faced new error:
```
% pip install underthesea[deep]==1.3.5       
zsh: no matches found: underthesea[deep]==1.3.5
```

When I install without [deep]
```
% pip install underthesea==1.3.5
ERROR: Could not find a version that satisfies the requirement underthesea-core==0.0.5a2 (from underthesea) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4a0, 0.0.4a1, 0.0.4a2, 0.0.4a3, 0.0.4a4, 0.0.4a5, 0.0.4a6, 0.0.4a8)
ERROR: No matching distribution found for underthesea-core==0.0.5a2
```

**Comment by rain1024** [comment]
@htluandc2 

```
zsh: no matches found: underthesea[deep]==1.3.5
```

I faced the same result when using pip with zsh. I haven't  figure out what is the problem here. For installation `underthesea[deep]`, I must run without zsh.

```
> % pip install underthesea==1.3.5
My enviroment:
% ipython
Python 3.9.13 (main, Aug 25 2022, 18:24:45)
```

Please try with older verion of python, such as python 3.8 or 3.7 and let me known what happends. I will invest in this issue further in next release (1.4.0)
