### ISSUE TITLE
Chunking result not as expected

### ISSUE THREAD

**Issue by pdhlong** [undertheseanlp/underthesea#598]
I want to use chunking to extract phrases from a sentence but when I test with the example in the document the result is different with no I-prefix.

![Screenshot 2022-11-17 114537](https://user-images.githubusercontent.com/59214698/202358523-321a8ba3-1bfc-4627-bfcd-e6f482564fcd.png)

**Comment by rain1024** [comment]
What is your expectation output with this sentence?

**Comment by pdhlong** [comment]
![image](https://user-images.githubusercontent.com/59214698/202360947-a6a40e1f-dc8c-48bf-955d-9cfbcff9d42f.png)
I thought this is the expected result

**Comment by pdhlong** [comment]
Thanh you. Btw, do you somehow work on keyword extraction for Vietnamese?

**Comment by rain1024** [comment]
> Thanh you. 
You're very welcome :D

>  do you somehow work on keyword extraction for Vietnamese?
Please create new `Issue` for new discussion
