### ISSUE TITLE
Can not download DI_Vietnamese-UVD dataset

### ISSUE THREAD

**Issue by KhuongDuy-Nguyen** [undertheseanlp/underthesea#641]
When I download the DI Vietnamese-UVD dataset by `underthesea download-data DI_Vietnamese-UVD`, it gives me this error. How can I fix that?

![image](https://user-images.githubusercontent.com/57941238/217308451-1f452a34-1482-4b42-98f1-0dc1275611d2.png)

**Comment by rain1024** [comment]
@KhuongDuy-Nguyen Thanks for reporting the issue.

The configuration of the dataset's filename was incorrect, I've fixed it and release new version 6.1.0. Please update underthesea and let me know if the code is now working.

**Comment by KhuongDuy-Nguyen** [comment]
@rain1024 It still error

![image](https://user-images.githubusercontent.com/57941238/217565596-ab20b57a-8edf-40d4-82d8-cde261fd93d7.png)

**Comment by rain1024** [comment]
> The process cannot access the file because it is being used by another process...

The bug related to opening a Zipfile has been fixed.

I also fixed errors related with `UTS2017_BANK`,  `VNESES`, `CP_Vientamese-UNC`, `VNTC` datasets.

Please update underthesea version 6.1.1 and let me know if the code is now working.

**Comment by KhuongDuy-Nguyen** [comment]
@rain1024  I can download them but I can't open it

![image](https://user-images.githubusercontent.com/57941238/217992925-8a737274-9a48-4f0d-b6b4-62ea348c1af6.png)

**Comment by rain1024** [comment]
The "UVD.bin" file is a dump created by pickle. To access its contents, you can use the following code

```py
import pickle

filepath = "UVD.bin"

with open(filepath, "rb") as f:
        data = pickle.load(f)

for item in data:
        print(item)
        print(data[item])
```

**Comment by KhuongDuy-Nguyen** [comment]
@rain1024 Got it, thanks for your support
