### ISSUE TITLE
Permission error when trying to remove the downloaded model zip file

### ISSUE THREAD

**Issue by BLKSerene** [undertheseanlp/underthesea#704]
When running on Windows CI with Python 3.11, a [permission error](https://app.circleci.com/pipelines/github/BLKSerene/Wordless/1009/workflows/1b0debb1-b305-4960-a5d9-e887d75c4da2/jobs/595) is raised when trying to remove the downloaded model zip file after the model content is extracted.

The problem might be that [the zip file is not closed properly](https://github.com/undertheseanlp/underthesea/blob/b04d52167320bdc4319f5070cd5f96d2e9d4e564/underthesea/model_fetcher.py#L126) before trying to delete the file. Maybe using `with` would be a better choice here.

**Comment by rain1024** [comment]
@BLKSerene, it sounds correct. What specific command did you use?

**Comment by BLKSerene** [comment]
The error occurred on CI with Windows Server 2019 and Python 3.11.4. I use the sentiment analysis function (`underthesea.sentiment`) which downloads the model automatically the first time the function is invoked
